const TRANS = {
  "zh-TW": {
    "defense":"防禦",
    "mystic":"神秘團隊",
    "valor":"英勇團隊",
    "instinct":"天才團隊",
    "team":"陣營",
    "vacancy":"剩餘空位",
    "own":"所屬",
    "optRate":"最佳比",
    "gymInfo":"我們會盡快更新此位置的道館，補給站信息",
    "region":"地區",
    "wildLife":"野生",
    "battleInformation":"對戰信息",
    "greatleague":"超級聯盟",
    "ultraleague":"高級聯盟",
    "masterleague":"大師聯盟",
    "atk":"攻擊",
    "sta":"防禦",
    "hp":"體力",
    "power":"戰鬥力",
    "opt":"戰力比",
    "information":"信息",
    "frostbiteInfestation":"凍傷感染區",
    "showOnMap":"顯示在地圖上",
    "level":"等級",
    "sourceText":"來源",
    "confirmed":"確認",
    "city":"城市",
    "cooldown":"冷卻",
    "bouns":"獎勵",
    "researchTasks":"調查研究",
    "time":"時間",
    "end":"結束",
    "hatch":"孵化",
    "sniperText":"狙擊",
    "raidText":"團體戰",
    "filedResrearch":"田野調查",
    "addPoint":"添加這個點",
    "minute":"分鐘",
    "shiny_check":"異色檢查",
    "feeds_noti":"提醒開關",
    "pokesniper":"寶可夢狙擊",
    "imoportSuccessInfo":"導入成功.若導入數據不全請檢查並修正文本格式和內容後再提交剩餘的部分.",
    "errorFormat":"您編輯的文本有錯誤的坐標格式請檢查並修改後再試",
    "importToList":"導入收藏列表",
    "choseImport":"選擇導入的方式",
    "jsonFile":"本地json文件",
    "textType":"文本模式",
    "editGPX":"編輯GPX",
    "local":"本地",
    "text":"文本",
    "importSuccess":"導入成功",
    "importFail":"導入失敗",
    "selectAll":"全選",
    "nestsplaceholder":"輸入ID或者Pokémon名稱",
    "lastUpdated":"最後更新時間",
    "nests":"巢穴",
    "noDeviceInfo":"如果沒有插入外設，將不允許使用推功能。",
    "country":"國家",
    "yield":"產量",
    "number":"編號",
    "addFavoritesSuccess":"您收藏的巢穴信息已添加至坐標收藏列表",
    "addFavorites":"添加到收藏",
    "newPokeStops":"新增道場",
    "newGyms":"新增補給站",
    "report":"上報",
    "generalSupply":"普通補給",
    "generalInfection":"普通感染區",
    "generalEncounter":"普通遭遇戰",
    "generalRescue":"普通營救任務",
    "general":"普通",
    "errorDriftValue":"請輸入1-10範圍的整數",
    "driftInterval":"(1-10 秒)",
    "frequency":"頻率",
    "drift":"原地漂移",
    "setting":"設置",
    "inputCity":"輸入城市名或首字母查詢",
    "locationText":"位置",
    "ifMakesure":"確認選擇",
    "setDefaultLan":"為默認語言嗎",
    "lanSet":"語言設置",
    "simplifiedChinese":"簡體中文",
    "traditionalChinese":"繁體中文",
    "english":"英語",
    "russian":"俄語",
    "german":"德語",
    "korean":"韓語",
    "thai":"泰語",
    "vietnam":"越南語",
    "japan":"日語",
    "reload":"重載",
    "help":"幫助",
    "ifGo":"是否前往",
    "all":"全部",
    "supply":"補給",
    "infectedArea":"感染區",
    "encounter":"遭遇戰",
    "rescueMission":"營救任務",
    "superiorHouse":"高級房子",
    "armory":"軍械庫",
    "shelterValue":"庇護所",
    "merchantStack":"商棧",
    "depot":"倉庫",
    "outpost":"前哨",
    "day":"天",
    "hour":"小時",
    'humanRaiders':'級的前哨',
    "rare":"稀有級補給",
    "epic":"史詩級補給",
    "legend":"傳奇級補給",
    "infectionRare":"稀有級感染區",
    "infectionEpic":"史詩級感染區",
    "infectionLegend":"傳奇級感染區",
    "encounterRare":"稀有級的遭遇戰",
    "encounterEpic":"史詩級的遭遇戰",
    "encounterLegend":"傳奇級的遭遇戰",
    "rescueRare":"稀有級的營救任務",
    "rescueEpic":"史詩級的營救任務",
    "rescueLegend":"传奇级的营救任务",
    "ordnance":"級的軍械庫,防禦時間",
    "shelter":"級的庇護所,防禦時間",
    "merchant":"級的商棧,防禦時間",
    "warehouse":"級的倉庫,防禦時間",
    "prompt":"提示",
    "news":"消息",
    "refresh":"刷新",
    "stopSim": "停止模擬",
    "enterLoc": "輸入地址或GPS坐標",
    "moveHere": "移動到這裡",
    "stopSimulation":"停止模擬並釋放對GPS數據的控制。（用於切換不同的iTools移動應用程序）",
    "stopSimulationInfo":"該應用程序現在無法運行。如果您準備再次使用它，請單擊重新加載按鈕。如果您準備使用另一個，請關閉該應用程序。",
    "restartForNormal": "注意:GPS模擬已經結束，但模擬效果仍然可能會持續一段時間，您可以重啟裝置讓GPS立刻恢復正常。",
    "gotoPointErrorMsg": "輸入的經緯度格式不正確",
    "gotoPointErrorTitle": "錯誤",
    "pointModelTitle": "瞬移模式",
    "lineModelTitle": "步行模式",
    "Distances": "距離",
    "Distances2": "距離",
    "TimeLeft": "用時",
    "mpointModelTitle": "自由路線模式",
    "pause": "暂停行走",
    "run": "开始行走",
    "cycle": "循环",
    "rockerMessage":"鍵盤W / S控制移動,鍵盤A / D控制方向",
    "loopMessage":"鼠標滾輪控制循環次數",
    "coord":"坐標",
    "copyed":"複製到剪貼板",
    "copyed1":"分享到iTools軟件用戶",
    "emptyHistoryMessage":"位置記錄為空",
    "historyDelMessage":"你想刪除該選項？",
    "historySaveErrorMessage":"位置格式不正確",
    "historySaveErrorTitle":"錯誤",
    "historyAddPlaceholder":"輸入標題",
    "confirmContent":"確認",
    "searchErrorMessage":"對不起，你輸入的地址信息或名稱無效:",
    "gpxErrFormat":"對不起，你拖動的文檔格式不支持。 請檢查文檔並拖動正確的文檔。",
    "gpxErrRuning":"對不起，Walk / Pin模式正在運行。 請關閉窗戶後嘗試再次拖動它。",
    "gpxErrSize":"對不起，無法將多個文檔拖入窗口。 請重新選擇。",
    "exportMessage":"導出GPX文檔",
    "returnLeft":"你上一個座標",
    "returnRight":"點擊'返回'立即回去",
    "repeatModeMsg":"點擊它來切換重複模式",
    "repeatModeMsgDx":"切換圓圈模式",
    "tooFar":"對不起，路線太遠無法從Google API獲取數據。請切換模式以重置路線。",
    "gpxProgressTitle":"提醒",
    "gpxProgressMessage":"我們檢測當前拖動的文檔跟你最後一次的文檔是一致的。請問你需要繼續嗎？",
    "group":"組",
    "FromOrigin":"當前點",
    "FromClipBoard":"剪貼板",
    "shortcut":"快捷鍵",
    "yes":"確認",
    "no":"取消",
    "go":"前往",
    "return":"返回",
    "gotit":"確認",
    "error":"失敗",
    "import":"導入",
    "export":"導出",
    "holdoff":"解鎖",
    "holdon":"鎖定",
    "speed":"速度",
    "iv":"IV偵測",
    "importGpx":"導入GPX文檔",
    "findMe":"我的位置",
    "mapZommIn":"地圖放大",
    "mapZommOut":"地圖縮小",
    "gpsError":"錯誤的GPS值",
    "subscribeInfo":"這項服務需要更高級的訂閱許可",
    "upgpx":"上傳路線",
    "addFavorite":"收藏路線",
    "unFavorite":"取消收藏",
    "nearby":"附近",
    "favorites":"收藏",
    "search":"搜索",
    "nearbyInputMsg":"輸入檢測的距離（1-5000米）",
    "generate":"生成",
    "stops_gyms":"補給站&道場",
    "stops":"補給站",
    "gyms":"道場",
    "length":"路徑長度",
    "apply_it":"使用路徑",
    "comingsoon":"即將推出",
    "nodata":"沒有數據",
    "nearErrorInput":"輸入的數值超出範圍",
    "upgpxsuccess":"上傳GPX文件成功",
    "upgpxfail":"上傳GPX文件失敗",
    "addFavoriteSuccess":"收藏成功",
    "addFavoriteFail":"收藏失敗",
    "unFavoritesSuccess":"取消收藏成功",
    "unFavoritesFail":"取消收藏失敗",
    "moreWindow":"管理多個設備",
    "subscribe_tit":"訂閱服務",
    "subscribe_message":"每月/每年的訂閱是獨立的，需要收取費用。 請不要輸入您的iTools許可證。 瞭解更多",
    "subscribe_input_msg":"已有激活碼？請輸入",
    "subscribe_link":"訂閱有什麼功能",
    "subscribe_subscribe":"立即訂閱",
    "subscribe_active":"激活",
    "subscribe_success":"成功",
    "subscribe_success_content":"訂閱成功",
    "subscribe_fail":"失敗",
    "subscribe_fail_content":"訂閱失敗",
    "randomfactor":"增加隨機參數來模擬真實行走",
    "randomfactorkm":"公里 速度變量",
    "randomfactortime":"秒 停頓時間",
    "unfold":"展開/隱藏功能",
    "automove":"GPS漂移",
    "mapZoomTip":"請將地圖放大到500米的比例尺內，以便完整顯示所有pokestops",
  },
  "zh-CN": {
    "avenger":"复仇者",
    "wantedList":"通缉列表",
    "blackList":"黑名单",
    "warnArea":"警戒区域",
    "choseCity":"选择主要城市",
    "noWantedListInfo":"暂时没有发现黑名单人员",
    "noBlackListInfo":"你还没有添加黑名单",
    "blackNameError":"黑名单不合法",
    "addBlackName":"添加黑名单",
    "editBlackName":"修改黑名单",
    "deleteBlackName":"确认删除黑名单吗",
    "areaNameError":"区域名输入不合法",
    "addWarnArea":"添加警戒区",
    "editWarnArea":"修改警戒区",
    "deleteWarnArea":"确认删除警戒区",
    "blackInputInfo":"请输入黑名单用户名称",
    "editArea":"编辑区域",
    "towerNameInput":"输入防守塔名称",
    "towerPointInput":"输入防守塔坐标",
    "defense":"防御",
    "mystic":"神秘团队",
    "valor":"英勇团队",
    "instinct":"天才团队",
    "team":"阵营",
    "own":"所属",
    "vacancy":"剩余空位",
    "optRate":"最佳比",
    "gymInfo":"我们会尽快更新此位置的道馆、补给站信息",
    "region":"地区",
    "wildLife":"野生",
    "battleInformation":"对战信息",
    "greatleague":"超级联盟",
    "ultraleague":"高级联盟",
    "masterleague":"大师联盟",
    "atk":"攻击",
    "sta":"防御",
    "hp":"体力",
    "power":"战斗力",
    "opt":"战力比",
    "information":"信息",
    "frostbiteInfestation":"冻伤感染区",
    "showOnMap":"显示在地图上",
    "level":"等级",
    "sourceText":"来源",
    "confirmed":"确认",
    "city":"城市",
    "cooldown":"冷却",
    "bouns":"奖励",
    "researchTasks":"调查研究",
    "time":"时间",
    "end":"结束",
    "hatch":"孵化",
    "sniperText":"狙击",
    "raidText":"团体战",
    "filedResrearch":"田野调查",
    "addPoint":"添加这个点",
    "minute":"分钟",
    "shiny_check":"异色检查",
    "feeds_noti":"提醒开关",
    "pokesniper":"宝可梦狙击",
    "imoportSuccessInfo":"导入成功.若导入数据不全请检查并修正文本格式和内容后再提交剩余的部分.",
    "errorFormat":"您编辑的文本有错误的坐标格式请检查并修改后再试",
    "importToList":"导入收藏列表",
    "choseImport":"选择导入的方式",
    "jsonFile":"本地json文件",
    "textType":"文本模式",
    "editGPX":"编辑GPX",
    "local":"本地",
    "text":"文本",
    "importSuccess":"导入成功",
    "importFail":"导入失败",
    "selectAll":"全选",
    "nestsplaceholder":"输入ID或者Pokémon名称",
    "lastUpdated":"最后更新时间",
    "nests":"巢穴",
    "noDeviceInfo":"如果没有插入外设，将不允许使用推功能。",
    "country":"国家",
    "yield":"产量",
    "number":"编号",
    "addFavoritesSuccess":"您收藏的巢穴信息已添加至坐标收藏列表",
    "addFavorites":"添加到收藏",
    "newPokeStops":"新增道场",
    "newGyms":"新增补给站",
    "report":"上报",
    "generalSupply":"普通补给",
    "generalInfection":"普通感染区",
    "generalEncounter":"普通遭遇战",
    "generalRescue":"普通营救任务",
    "general":"普通",
    "errorDriftValue":"请输入1-10范围的整数",
    "driftInterval":"(1-10 秒)",
    "frequency":"频率",
    "drift":"原地漂移",
    "setting":"设置",
    "inputCity":"输入城市名或首字母查询",
    "locationText":"位置",
    "ifMakesure":"确认选择",
    "setDefaultLan":"为默认语言吗",
    "lanSet":"语言设置",
    "simplifiedChinese":"简体中文",
    "traditionalChinese":"繁体中文",
    "english":"英语",
    "russian":"俄语",
    "german":"德语",
    "korean":"韩语",
    "thai":"泰语",
    "vietnam":"越南语",
    "japan":"日语",
    "reload":"重载",
    "help":"帮助",
    "ifGo":"是否前往",
    "all":"全部",
    "supply":"补给",
    "infectedArea":"感染区",
    "encounter":"遭遇战",
    "rescueMission":"营救任务",
    "superiorHouse":"高级房子",
    "armory":"军械库",
    "shelterValue":"庇护所",
    "merchantStack":"商栈",
    "depot":"仓库",
    "outpost":"前哨",
    "day":"天",
    "hour":"小时",
    'humanRaiders':'级的前哨',
    "rare":"稀有级补给",
    "epic":"史诗级补给",
    "legend":"传奇级补给",
    "infectionRare":"稀有级感染区",
    "infectionEpic":"史诗级感染区",
    "infectionLegend":"传奇级感染区",
    "encounterRare":"稀有级的遭遇战",
    "encounterEpic":"史诗级的遭遇战",
    "encounterLegend":"传奇级的遭遇战",
    "rescueRare":"稀有级的营救任务",
    "rescueEpic":"史诗级的营救任务",
    "rescueLegend":"传奇级的营救任务",
    "ordnance":"级的军械库防御时间",
    "shelter":"级的庇护所,防御时间",
    "merchant":"级的商栈,防御时间",
    "warehouse":"级的仓库,防御时间",
    "prompt":"提示",
    "news":"消息",
    "refresh":"刷新",
    "stopSim": "停止模拟",
    "enterLoc": "输入地址或GPS坐标",
    "moveHere": "移动到这里",
    "restartForNormal": "注意:GPS模拟已经结束，但模拟效果仍然可能会持续一段时间，您可以重启设备让GPS立刻恢复正常。",
    "stopSimulation":"停止模拟并释放对GPS数据的控制。（用于切换不同的iTools移动应用程序）",
    "stopSimulationInfo":"该应用程序现在无法运行。如果您准备再次使用它，请单击重新加载按钮。如果您准备使用另一个，请关闭该应用程序。",
    "gotoPointErrorMsg": "输入的经纬度格式不正确",
    "gotoPointErrorTitle": "错误",
    "pointModelTitle": "瞬移模式",
    "lineModelTitle": "步行模式",
    "Distances": "距离",
    "Distances2": "距离",
    "TimeLeft": "用时",
    "mpointModelTitle": "自由路线模式",
    "pause": "暂停行走",
    "run": "开始行走",
    "cycle": "循环",
    "rockerMessage":"键盘 / S控制移動,键盘 / D控制方向",
    "loopMessage":"鼠标滚轮控制循环次数",
    "coord":"坐标",
    "copyed":"复制到剪贴板",
    "copyed1":"分享到iTools用户",
    "emptyHistoryMessage":"位置记录为空",
    "historyDelMessage":"你想删除这选项？",
    "historySaveErrorMessage":"位置格式不正确",
    "historySaveErrorTitle":"错误",
    "historyAddPlaceholder":"输入标题",
    "confirmContent":"确认",
    "searchErrorMessage":"对不起，你输入的地址信息或名称无效:",
    "gpxErrFormat":"对不起，你拖动的文件格式不支持。 请检查文件并拖动正确的文件。",
    "gpxErrRuning":"对不起，Walk / Pin模式正在运行。 请关闭窗户后尝试再次拖动它。",
    "gpxErrSize":"对不起，无法将多个文件拖入窗口。 请重新选择。",
    "exportMessage":"导出GPX文件",
    "returnLeft":"你上一个坐标",
    "returnRight":"点击'返回'立即回去",
    "repeatModeMsg":"点击它来切换重复模式",
    "repeatModeMsgDx":"切换圆圈模式",
    "tooFar":"对不起，路线太远无法从Google API获取数据。请切换模式以重置路线。",
    "gpxProgressTitle":"提醒",
    "gpxProgressMessage":"我们检测到当前拖动的文件跟你最后一次的文件是一致的。请问你需要继续吗？",
    "group":"组",
    "FromOrigin":"当前点",
    "FromClipBoard":"剪贴板",
    "shortcut":"快捷键",
    "yes":"确认",
    "no":"取消",
    "go":"前往",
    "return":"返回",
    "gotit":"确认",
    "error":"错误",
    "import":"导入",
    "export":"导出",
    "holdoff":"解锁",
    "holdon":"锁定",
    "speed":"速度",
    "iv":"IV侦测",
    "importGpx":"导入GPX文件",
    "findMe":"我的位置",
    "mapZommIn":"地图放大",
    "mapZommOut":"地图缩小",
    "gpsError":"错误的GPS值",
    "subscribeInfo":"这项服务需要更高级的订阅许可",
    "upgpx":"上传路线",
    "addFavorite":"收藏路线",
    "unFavorite":"取消收藏",
    "nearby":"附近",
    "favorites":"收藏",
    "search":"搜索",
    "nearbyInputMsg":"输入检测的距离（1-5000米）",
    "generate":"生成",
    "stops_gyms":"补给站&道场",
    "stops":"补给站",
    "gyms":"道场",
    "length":"路径长度",
    "apply_it":"使用路径",
    "comingsoon":"即将退出",
    "nodata":"没有数据",
    "nearErrorInput":"输入的数值超出范围",
    "upgpxsuccess":"上传GPX文件成功",
    "upgpxfail":"上传GPX文件失败",
    "addFavoriteSuccess":"收藏成功",
    "addFavoriteFail":"收藏失败",
    "unFavoritesSuccess" : "取消收藏成功",
    "unFavoritesFail" : "取消收藏失败",
    "moreWindow":"管理多个设备",
    "subscribe_tit":"订阅服务",
    "subscribe_message":"每月/每年的订阅是独立的，需要收取费用。请不要输入您的iTools许可证。了解更多",
    "subscribe_input_msg":"已有激活码？请输入",
    "subscribe_link":"订阅有什么功能",
    "subscribe_subscribe":"立即订阅",
    "subscribe_active":"激活",
    "subscribe_success":"成功",
    "subscribe_success_content":"订阅成功",
    "subscribe_fail":"失败",
    "subscribe_fail_content":"订阅失败",
    "randomfactor":"增加随机因素来模拟真实行走",
    "randomfactorkm":"公里 速度变量",
    "randomfactortime":"秒 停留时间",
    "unfold":"展开/隐藏功能",
    "automove":"GPS漂移",
    "mapZoomTip": "请将地图放大到500米的比例尺内，以便完整显示所有pokestops",
  },
  "en-US": {
    "currentPoint":"当前坐标",
    "avenger":"复仇者",
    "wantedList":"通缉列表",
    "blackList":"黑名单",
    "warnArea":"警戒区域",
    "choseCity":"选择主要城市",
    "noWantedListInfo":"暂时没有发现黑名单人员",
    "noBlackListInfo":"你还没有添加黑名单",
    "blackNameNoChange":"黑名单没有修改",
    "blackNameLengthError":"最多只能添加12个黑名单",
    "blackNameError":"黑名单不合法",
    "addBlackName":"添加黑名单",
    "editBlackName":"修改黑名单",
    "deleteBlackName":"确认删除黑名单吗",
    "pointRange":"纬度范围：-90.0000~90.0000,经度范围：-180.0000~180.0000",
    "pointError":"坐标点输入不合法",
    "warnAreaLengthError":"最多只能添加20个区域",
    "addWarnArea":"添加警戒区",
    "editWarnArea":"修改警戒区",
    "deleteWarnArea":"确认删除警戒区域吗",
    "blackInputInfo":"请输入黑名单用户名称",
    "editArea":"编辑区域",
    "towerNameInput":"输入防守塔名称",
    "towerPointInput":"输入防守塔坐标",
    "defense":"Defense",
    "mystic":"Mystic",
    "valor":"Valor",
    "instinct":"Instinc",
    "team":"Team",
    "own":"own",
    "vacancy":"Vacancy",
    "optRate":"Optimal Rate",
    "gymInfo":"we will update the Gyms and Stops information of this location asap.",
    "region":"Area",
    "wildLife":"Wild Finder",
    "battleInformation":"Battle Information",
    "greatleague":"Great League",
    "ultraleague":"Ultra League",
    "masterleague":"Master League",
    "atk":"atk",
    "sta":"sta",
    "hp":"hp",
    "power":"Power",
    "opt":"opt",
    "information":"INFO",
    "frostbiteInfestation":"Frostbite infestation",
    "showOnMap":"Display on Map",
    "level":"Level",
    "sourceText":"From",
    "confirmed":"Confirmed",
    "city":"City",
    "cooldown":"Cooldown",
    "bouns":"Bouns",
    "researchTasks":"Research Tasks",
    "time":"Time",
    "end":"end",
    "hatch":"hatch",
    "sniperText":"PokeSniper",
    "raidText":"Raid",
    "filedResrearch":"Filed Research",
    "addPoint":"Add to pin",
    "minute":"Minutes",
    "shiny_check":"Shiny check",
    "feeds_noti":"Feeds Notification",
    "pokesniper":"PokeSniper",
    "imoportSuccessInfo":"Import succeed.If the data is not completed, please check and fix it first. Then edit the rest data and submit it again.",
    "errorFormat":"There are something wrong with your entered coordinates.Please check  and fix it before you retry.",
    "importToList":"Favorites Import",
    "choseImport":"select the way to import",
    "jsonFile":"Json Files",
    "textType":"Text Field",
    "editGPX":"Edit GPX",
    "local":"Local",
    "text":"Text",
    "importSuccess":"Import success.",
    "importFail":"Import failed.",
    "selectAll":"Select All",
    "nestsplaceholder":"Enter Name/ID for filtering",
    "lastUpdated":"Last updated at",
    "nests":"Nests",
    "noDeviceInfo":"It is not allowed to use Push function if the dongle has not been plugged。",
    "country":"Country",
    "yield":"Amount",
    "number":"ID",
    "addFavoritesSuccess":"Your favorite nest information has been added to the coordinate collection list",
    "addFavorites":"Add to favorites",
    "newPokeStops":"New PokeStops",
    "newGyms":"New Gyms",
    "report":"Report",
    "generalSupply":"General supply",
    "generalInfection":"General infestation",
    "generalEncounter":"General encounter",
    "generalRescue":"General rescue mission",
    "general":"general",
    "errorDriftValue":"Please enter an integer from 1 to 10",
    "driftInterval":"(1-10 seconds)",
    "frequency":"Frquency ",
    "drift":"GPS Drifting",
    "setting":"Settings",
    "inputCity":"Enter the city name or initials query",
    "locationText":"Location",
    "ifMakesure":"Confirm selection",
    "setDefaultLan":"to be default language",
    "lanSet":"Language settings",
    "simplifiedChinese":"Simplified Chinese",
    "traditionalChinese":"Traditional Chinese",
    "english":"English",
    "russian":"Russian",
    "german":"German",
    "korean":"Korean",
    "thai":"Thai",
    "vietnam":"Vietnamese",
    "japan":"Japanese",
    "reload":"Reload",
    "help":"Help",
    "ifGo":"if go",
    "all":"All",
    "supply":"Supply",
    "infectedArea":"Infestation",
    "encounter":"Encounter",
    "rescueMission":"Rescue mission",
    "superiorHouse":"Superior house",
    "armory":"Armory",
    "shelterValue":"Shelter",
    "merchantStack":"Trading post",
    "depot":"Warehouse",
    "outpost":"Raider outpost",
    "day":"day",
    "hour":"hour",
    'humanRaiders':'-level raider outpost',
    "rare":"Rare supply",
    "epic":"Epic supply",
    "legend":"Legendary supply",
    "infectionRare":"Rare infestation",
    "infectionEpic":"Epic infestation",
    "infectionLegend":"Legendary infestation",
    "encounterRare":"Rare level encounter",
    "encounterEpic":"Epic encounter",
    "encounterLegend":"Legendary encounter",
    "rescueRare":"Rare rescue mission",
    "rescueEpic":"Epic rescue mission",
    "rescueLegend":"Legendary rescue mission",
    "ordnance":"-level armory, defense time",
    "shelter":"-level shelter, defense time",
    "merchant":"-level trading post, defensive time",
    "warehouse":"-level warehouse, defense time",
    "prompt":"prompt",
    "news":"Push",
    "refresh":"Refresh",
    "stopSim": "Stop Simulation",
    "enterLoc": "Enter an adr/GPS coordinates",
    "moveHere": "Move here",
    "stopSimulation":"Stop simulation and release the control of GPS data.(It is used to switch different iTools mobile apps)",
    "stopSimulationInfo":"The app is not working now.If you are ready to use it again, please click the reload button.If you are ready to use another one, please close the app.",
    "restartForNormal": "Notice: Your GPS data recovered. But GPS simulation might be lasting for some time even you have stopped it. You＇d better reboot your iPhone that makes your GPS return to normal soon.",
    "gotoPointErrorMsg": "Failed to move to the target location. The input value must be GPS format. Please try again.",
    "gotoPointErrorTitle": "Failed to move",
    "pointModelTitle": "Move mode",
    "lineModelTitle": "Walk mode",
    "Distances": "Route/A-B Distances",
    "Distances2": "Distances",
    "TimeLeft": "TimeLeft",
    "mpointModelTitle": "Pin mode",
    "pause": "Pause",
    "run": "Start",
    "cycle": "Cycle",
    "rockerMessage":"Keyboard W  / S to control movement Keyboard A / D to control direction",
    "loopMessage":"mouse wheel to control the times accurately",
    "coord":"Coord",
    "copyed":"Copy to clipboard",
    "copyed1":"Share to iTools users",
    "emptyHistoryMessage":"Your current group is empty.",
    "historyDelMessage":"Do you want to delete this item? ",
    "historySaveErrorMessage":"The X/Y value or format is illegal.",
    "historySaveErrorTitle":"Failed",
    "historyAddPlaceholder":"Enter your heading name",
    "confirmContent":"Confirm",
    "searchErrorMessage":"Sorry, the entered longitude and latitude are illegal.",
    "gpxErrFormat":"Sorry, the format of dragged file is illegal. Please check the file and drag the correct one.",
    "gpxErrRuning":"Sorry, the Walk/Pin Mode is running. Please close the windows and try to drag it again.",
    "gpxErrSize":"Sorry, unable to drag multiple files into the window. Please drag the single one again.",
    "exportMessage":"Export the GPX file",
    "returnLeft":"Your previous coords",
    "returnRight":"Click Return to get back at once",
    "repeatModeMsg":"Tap it to switch Repeat Mode",
    "repeatModeMsgDx":"Tap it to Switch Circle Mode",
    "tooFar":"Sorry, the route is too far to get the data from Google API. Please switch Pin Mode to reset the route. ",
    "gpxProgressTitle":"Reminder",
    "gpxProgressMessage":"We have detected your dragging GPX is the same as your previous one. Do you want to continue on?",
    "group":"Group name",
    "FromOrigin":"From Origin",
    "FromClipBoard":"From ClipBoard",
    "shortcut":"Shortcut",
    "yes":"Yes",
    "no":"Cancel",
    "go":"Go",
    "return":"Return",
    "gotit":"Got it",
    "error":"Error",
    "import":"Import",
    "export":"Export",
    "holdoff":"Hold off",
    "holdon":"Hold on",
    "speed":"Speed",
    "iv":"IV checker",
    "importGpx":"Import GPX file",
    "findMe":"Center on me",
    "mapZommIn":"Map zoom in",
    "mapZommOut":"Map zoom out",
    "gpsError":"Wrong GPS value",
    "subscribeInfo":"The service is required with silver subscription",
    "upgpx":"Upload the GPX",
    "addFavorite":"Add to Favorites",
    "unFavorite":"UnFavorite",
    "nearby":"Nearby",
    "favorites":"Favorites",
    "search":"Search",
    "nearbyInputMsg":"Enter distance（1/m - 5000/m）",
    "generate":"Generate",
    "stops_gyms":"Stops&Gyms",
    "stops":"Stops",
    "gyms":"Gyms",
    "length":"Length",
    "apply_it":"Apply it",
    "comingsoon":"Coming Soon",
    "nodata":"No Data",
    "nearErrorInput":"Invalid number. Please enter in its range of validity.",
    "upgpxsuccess":"Upload the GPX successfully",
    "upgpxfail":"Upload the GPX fail",
    "addFavoriteSuccess":"Add to Favorites successfully",
    "addFavoriteFail":"Add to Favorites fail",
    "unFavoritesSuccess" : "Delete it from Favorites successfully",
    "unFavoritesFail" : "Failed to delete it from Favorites",
    "moreWindow":"Manage multiple devices",
    "subscribe_tit":"Subscription Service",
    "subscribe_message":"Monthly/Annual Subscriptions are independent and required to charge. Please Do not enter your Premium/Platinum License. Learn more via ",
    "subscribe_input_msg":"Already had keys? Please fill in.",
    "subscribe_link":"What’s new for subscription?",
    "subscribe_subscribe":"Subscribe Now",
    "subscribe_active":"Activate",
    "subscribe_success":"Successfully",
    "subscribe_success_content":"Successfully subscribed",
    "subscribe_fail":"Failed",
    "subscribe_fail_content":"Failed to subscribe",
    "randomfactor":"Add the random element to walk as a human",
    "randomfactorkm":"km variable",
    "randomfactortime":"sec still time",
    "unfold":"Unfold / Hide features",
    "automove":"GPS Drifting",
    "mapZoomTip": "Please zoom in the map within 500-meter measuring scale in order to display all the pokestops completely",
  },
  "ru-RU": {
    "defense":"обороны",
    "mystic":"Загадочная команда",
    "valor":"Героическая команда",
    "instinct":"Гениальная команда",
    "team":"лагерь",
    "own":"Принадлежит",
    "vacancy":"комната",
    "optRate":"Оптимальное соотношение",
    "gymInfo":"Мы будем обновлять информацию о павильоне и станции снабжения в этом месте как можно скорее.",
    "region":"область",
    "wildLife":"дикий",
    "battleInformation":"Боевая информация",
    "greatleague":"Суперлига",
    "ultraleague":"Высшая лига",
    "masterleague":"Мастер Лига",
    "atk":"атака",
    "sta":"обороны",
    "hp":"Физическая сила",
    "power":"Боевая мощь",
    "opt":"Соотношение войны",
    "information":"информация",
    "frostbiteInfestation":"Обмороженные зараженные области",
    "showOnMap":"Показать на карте",
    "level":"оценка Etc",
    "sourceText":"источник",
    "confirmed":"подтвердить",
    "city":"город",
    "cooldown":"охлаждение",
    "bouns":"вознаграждение",
    "researchTasks":"исследование",
    "time":"время",
    "sniperText":"бекас",
    "raidText":"Командная битва",
    "filedResrearch":"Полевое расследование",
    "addPoint":"Добавить этот пункт",
    "minute":"минут",
    "shiny_check":"Блестящая проверка",
    "feeds_noti":"Уведомление о фидах",
    "pokesniper":"PokeSniper",
    "imoportSuccessInfo":"Импорт успешно. Если данные импорта не завершены, проверьте и скорректируйте текстовый формат и содержимое перед отправкой оставшейся части.",
    "errorFormat":"Текст, который вы отредактировали, имеет неправильный формат координат. Проверьте и измените его и повторите попытку.",
    "importToList":"Импорт списка избранного",
    "choseImport":"Выберите способ импорта",
    "jsonFile":"Локальный файл json",
    "textType":"Текстовый режим",
    "editGPX":"Изменить GPX",
    "local":"местный",
    "text":"текст",
    "importSuccess":"Успешно импортировано",
    "importFail":"Ошибка импорта",
    "selectAll":"Выбрать все",
    "nestsplaceholder":"Введите имя / идентификатор для фильтрации",
    "lastUpdated":"Время обновления",
    "nests":"гнезда",
    "noDeviceInfo":"Функция Push не допускается, если никакие периферийные устройства не подключены。",
    "country":"страна",
    "yield":"выход",
    "number":"номер",
    "addFavoritesSuccess":"Ваша любимая информация о гнезде была добавлена в список коллекции координат",
    "addFavorites":"Добавить в избранное",
    "newPokeStops":"newPokeStops",
    "newGyms":"Новая станция снабжения",
    "report":"сообщается",
    "generalSupply":"Обычная поставка",
    "generalInfection":"Общая зараженная область",
    "generalEncounter":"Обычная встреча",
    "generalRescue":"Обычная миссия по спасению",
    "general":"обычный",
    "errorDriftValue":"Введите целое число от 1 до 10",
    "driftInterval":"Дрейф один раз",
    "frequency":"частота",
    "drift":"Дрейф in-situ",
    "setting":"устанавливать",
    "inputCity":"Введите название города или запрос инициалов",
    "locationText":"расположение",
    "ifMakesure":'Вы действительно хотите выбрать',
    "setDefaultLan":'в качестве языка по умолчанию?',
    "lanSet":'Настройка языка',
    "simplifiedChinese":'/',
    "traditionalChinese":'/',
    "english":'/',
    "russian":'Pусский',
    "german":'/',
    "korean":'/',
    "thai":'/',
    "vietnam":'/',
    "japan":'/',
    "reload":'Перезарядка',
    "help":'Помощь',
    "ifGo":'Идти?',
    "all":'Все',
    "supply":'Припасы',
    "infectedArea":'Зараженная зона',
    "encounter":'Схватка',
    "rescueMission":'Спасательная миссия',
    "superiorHouse":'Высший дом',
    "armory":'Арсенал',
    "shelterValue":'Укрытие',
    "merchantStack":'Торговый пост',
    "depot":'Склад',
    "outpost":'Опорный пункт',
    "day":'день',
    "hour":'час',
    "humanRaiders":'-уровень опорного пункта',
    "rare":'Редкий боеприпас',
    "epic":'Эпичный боеприпас',
    "legend":'Легендарный боеприпас',
    "infectionRare":'Редкое заражение',
    "infectionEpic":'Эпичное заражение',
    "infectionLegend":'Легендарное заражение',
    "encounterRare":'Редкий уровень схватки',
    "encounterEpic":'Эпичная схватка',
    "encounterLegend":'Легендарная схватка',
    "rescueRare":'Редкая спасательная миссия',
    "rescueEpic":'Эпичная спасательная миссия',
    "rescueLegend":'Легендарная спасательная миссия',
    "ordnance":'-уровень времени защиты арсенала',
    "shelter":'-уровень времени защиты укрытия',
    "merchant":'-уровень времени защиты торгового поста',
    "warehouse":'-уровень времени защиты склада',
    "prompt":'Подсказка',
    "news":'Толкнуть',
    "refresh":'Обновить',
    "stopSim":'Нажмите кнопку "Stop Simulation"',
    "enterLoc":'Введите координаты',
    "moveHere":'Передвинуть сюда',
    "stopSimulation":'Нажмите кнопку восстановления местоположения "Stop Simulation" и деактивируйте управление данными GPS (чтобы переключаться между различными мобильными приложениями iTools)',
    "stopSimulationInfo":'Приложение временно не работает. Нажмите ""Обновить"" что перезапустить приложение. Если вы хотите войти через другое приложение, нажмите Закрыть".',
    "restartForNormal":'Примечание: данные GPS восстановлены,но имитация местоположения может продолжаться еще некоторое время, даже после остановки. Рекомендуется перезагрузить iPhone, чтобы вернуть действительные координаты GPS.',
    "gotoPointErrorMsg":'Перемещение в заданное местоположение не удалось. Входные значения должны быть в формате GPS. Повторите попытку.',
    "gotoPointErrorTitle":'Перемещение не удалось',
    "pointModelTitle":'Режим перемещения',
    "lineModelTitle":'Режим ходьбы',
    "Distances":'Маршрут/Расстояния A-B',
    "Distances2":'Расстояние',
    "TimeLeft":'Осталось времени',
    "mpointModelTitle":'Режим Pin',
    "pause":'Пауза',
    "run":'Начать',
    "cycle":'Цикл',
    "coord":'Координаты',
    "copyed":'Скопировать в буфер',
    "copyed1":"Поделитесь с пользователями iTools",
    "emptyHistoryMessage":'Ваш список координат пуст',
    "historyDelMessage":'Хотите удалить выбранный элемент?',
    "historySaveErrorMessage":'Значение X/Y или формат не действительны',
    "historySaveErrorTitle":'Не удалось',
    "historyAddPlaceholder":'Введите название',
    "confirmContent":'Потвердить',
    "searchErrorMessage":'Отсутствуют параметры или имена для ввода:',
    "gpxErrFormat":'Недопустимый формат перемещаемого файла. Переместите необходимый файл после проверки',
    "gpxErrRuning":'Активирован режим ходьбы/Pin.Закройте окно и повторите попытку перемещения файла',
    "exportMessage":'Экспорт файла GPX',
    "returnLeft":'Ваши предыдущие координаты',
    "returnRight":'Для возврата нажмите кнопку "Назад"',
    "repeatModeMsg":'Коснитесь для переключения в режим повторения',
    "repeatModeMsgDx":'Коснитесь для переключения в режим цикла',
    "tooFar":'Маршрут находится слишком далеко, чтобы получить данные из Google API. Перейдите в режим Pin, чтобы сбросить маршрут',
    "gpxProgressTitle":'Напоминание',
    "gpxProgressMessage":'Перемещаемый файл GPX совпадает с предыдущим. Продолжить?',
    "group":'Имя группы',
    "FromOrigin":'Из Origin',
    "FromClipBoard":'Из буфера',
    "shortcut":'Быстрый доступ',
    "yes":'Да',
    "no":'Нет',
    "go":'Вперед',
    "return":'Назад',
    "gotit":'Принято',
    "error":'Ошибка',
    "import":'Импорт',
    "export":'Экспорт',
    "holdoff":'Снять с паузы',
    "holdon":'Поставить на паузу',
    "speed":'Скорость',
    "importGpx":'Импорт файла GPX',
    "findMe":'Показать мое местоположение',
    "mapZommIn":'Приблизить карту',
    "mapZommOut":'Отдалить карту',
    "gpsError":'Неправильное значение GPS',
    "upgpx":'Загрузить GPX',
    "addFavorite":'Добавить в Избранное',
    "unFavorite":'Удалить из папки Избранное',
    "nearby":'Поблизости',
    "favorites":'Избранное',
    "search":'Поиск',
    "nearbyInputMsg":'Ввести расстояние (/m - /m)',
    "generate":'Создать',
    "stops_gyms":'Стопы и гимы',
    "stops":'Стопы',
    "gyms":'Гимы',
    "length":'Длина',
    "apply_it":'Применить',
    "comingsoon":'Скоро',
    "nodata":'Данные отсутствуют',
    "nearErrorInput":'Недопустимый номер. Введите номер из диапазона допустимых значений.',
    "upgpxsuccess":'Успешная загрузка файла GPX',
    "upgpxfail":'Ошибка загрузки файла GPX',
    "addFavoriteSuccess":'Успешно добавлено в Избранное',
    "addFavoriteFail":'Ошибка добавления в папку Избранное',
    "unFavoritesSuccess":'Успешно удалено из папки Избранное',
    "unFavoritesFail":'Ошибка при удаленнии из папки Избранное',
    "subscribe_active":'Активировать',
    "subscribe_success":'Успешно',
    "subscribe_fail":'Ошибка',
    "randomfactor":'Добавьте случайный элемент для игры за человека',
    "randomfactorkm":'переменная величина, км',
    "randomfactortime":'время без движения, сек',
    "unfold":'Раскрыть / Скрыть свойства',
    "automove":'"Дрожание" GPS',
    "netTip":'Сеть не доступна.',
    "gpsTip":'Ваше текущее местоположение зависит от сети. Введите виртуальные координаты GPS и сначала переместитесь в заданное ими местоположение перед тем как войти в игру, использующую GPS.',
    "arrivedTip":'Вы прибыли в пункт назначения!',
    "deviceTip":'Связь с вашим устройством потеряна. Вы можете продолжить при наличии доступа к сети.',
    "jsonTitle":'Список JSON',
    "gpxTitle":'Список GPX',
    "renameTitle":'Переименовать',
    "renameBtn":'Переименовать',
    "backBtn":'Назад',
    "doneBtn":'Готово',
    "delBtn":'Удалить',
    "mapZoomTip": "Пожалуйста, увеличьте масштаб карты в пределах 500-метровой измерительной шкалы, чтобы полностью отобразить все покстопы",
  },
  "de-DE": {
    "defense":"Verteidigung",
    "mystic":"Geheimnisvolles Team",
    "valor":"Heroisches Team",
    "instinct":"Genius-Team",
    "team":"Lager",
    "own":"Eigenes",
    "vacancy":"Vakanz",
    "optRate":"Optimales Verhältnis",
    "gymInfo":"Wir werden die Informationen des Pavillons und der Versorgungsstation an diesem Ort so schnell wie möglich aktualisieren.",
    "region":"Bereich",
    "wildLife":"Wild",
    "battleInformation":"Kampfinformationen",
    "greatleague":"Super Liga",
    "ultraleague":"Oberliga",
    "masterleague":"Master League",
    "atk":"Angriff",
    "sta":"Verteidigung",
    "hp":"Körperliche Stärke",
    "power":"Kampfkraft",
    "opt":"Kriegsverhältnis",
    "information":"INFO",
    "frostbiteInfestation":"Mit Erfrierungen infizierter Bereich",
    "showOnMap":"Auf der Karte anzeigen",
    "level":"Ebene",
    "sourceText":"Quelle",
    "confirmed":"Bestätigen",
    "city":"Stadt",
    "cooldown":"Abkühlung",
    "bouns":"Belohnung",
    "researchTasks":"Untersuchung",
    "time":"Zeit",
    "sniperText":"Scharfschütze",
    "raidText":"Teamkampf",
    "filedResrearch":"Felduntersuchung",
    "addPoint":"Fügen Sie diesen Punkt hinzu",
    "minute":"Minute",
    "shiny_check":"Glänzender Check",
    "feeds_noti":"Feeds-Benachrichtigung",
    "pokesniper":"PokeSniper",
    "imoportSuccessInfo":"Der Import ist erfolgreich: Wenn die Importdaten nicht vollständig sind, überprüfen und korrigieren Sie bitte das Textformat und den Inhalt, bevor Sie den restlichen Teil senden.",
    "errorFormat":"Der Text, den Sie bearbeitet haben, hat das falsche Koordinatenformat.",
    "importToList":"Favoritenliste importieren",
    "choseImport":"Wählen Sie aus, wie Sie importieren möchten",
    "jsonFile":"Lokale Json-Datei",
    "textType":"Textmodus",
    "editGPX":"GPX bearbeiten",
    "local":"Lokal",
    "text":"Text",
    "importSuccess":"Erfolgreich importiert",
    "importFail":"Import fehlgeschlagen",
    "selectAll":"Wählen Sie Alle",
    "nestsplaceholder":"Geben Sie Name / ID zum Filtern ein",
    "lastUpdated":"Zuletzt aktualisiert um",
    "nests":"Nester",
    "noDeviceInfo":"Die Push-Funktion ist nicht erlaubt, wenn keine Peripheriegeräte angeschlossen sind。",
    "country":"Land",
    "yield":"Ausbeute",
    "number":"Nummer",
    "addFavoritesSuccess":"Ihre Lieblingsnest-Informationen wurden der Koordinatensammelliste hinzugefügt",
    "addFavorites":"Zu Favoriten hinzufügen",
    "newPokeStops":"Füge ein Dojo hinzu",
    "newGyms":"Neue Versorgungsstation",
    "report":"Bericht",
    "generalSupply":"Gewöhnliche Versorgung",
    "generalInfection":"Häufiger infizierter Bereich",
    "generalEncounter":"Gewöhnliche Begegnung",
    "generalRescue":"Gewöhnliche Rettungsmission",
    "general":"Häufig",
    "errorDriftValue":"Bitte geben Sie eine ganze Zahl zwischen 1 und 10 ein",
    "driftInterval":"Drift einmal",
    "frequency":"Frequenz",
    "drift":"In-situ-Drift",
    "setting":"Einstellung",
    "inputCity":"Geben Sie den Stadtnamen oder die Initialabfrage ein",
    "locationText":"Standort",
    "ifMakesure":'Möchten Sie wirklich',
    "setDefaultLan":'als Standardsprache auswählen?',
    "lanSet":'Spracheinstellung',
    "simplifiedChinese":'/',
    "traditionalChinese":'/',
    "english":'/',
    "russian":'/',
    "german":'Deutsch',
    "korean":'/',
    "thai":'/',
    "vietnam":'/',
    "japan":'/',
    "reload":'Neu laden',
    "help":'Hilfe',
    "ifGo":'wenn Du gehst',
    "all":'Alle',
    "supply":'Versorgung',
    "infectedArea":'Infektion',
    "encounter":'Begegnung',
    "rescueMission":'Rettungsmission',
    "superiorHouse":'Oberhaus',
    "armory":'Waffenarsenal',
    "shelterValue":'Unterkunft',
    "merchantStack":'Handelsposten',
    "depot":'Lager',
    "outpost":'Räuberaußenposten',
    "day":'Tag',
    "hour":'Stunde',
    "humanRaiders":'-Ebene-Räuberaußenposten',
    "rare":'Seltene Versorgung',
    "epic":'Epische Versorgung',
    "legend":'Legendäre Versorgung',
    "infectionRare":'Seltene Infektion',
    "infectionEpic":'Epische Infektion',
    "infectionLegend":'Legendäre Infektion',
    "encounterRare":'Seltene Ebenenbegegnung',
    "encounterEpic":'Epische Begegnung',
    "encounterLegend":'Legendäre Begegnung',
    "rescueRare":'Seltene Rettungsmission',
    "rescueEpic":'Epische Rettungsmission',
    "rescueLegend":'Legendäre Rettungsmission',
    "ordnance":'-Ebenen-Waffenarsenal Verteidigungszeit',
    "shelter":'-Ebenen-Unterkunft Verteidigungszeit',
    "merchant":'-Ebenen-Handelsposten Verteidigungszeit',
    "warehouse":'-Ebenen-Lager Verteidigungszeit',
    "prompt":'Eingabeaufforderung',
    "news":'Push-Benachrichtigung',
    "refresh":'Aktualisieren',
    "stopSim":'Simulation stoppen',
    "enterLoc":'ADR/GPS-Koordinaten eingeben',
    "moveHere":'Hierher gehen',
    "stopSimulation":'Die Simulation stoppen und das Bedienungselement der GPS-Daten freigeben (es wird verwendet, um zwischen verschiedenen mobilen iTools-Apps zu wechseln)',
    "stopSimulationInfo":'Die App ist gerade nicht aktiv. Wenn Du sie wieder verwenden möchtest, klicke bitte hier auf die "Reload"-Taste. Wenn Du bereits eine andere verwendest, schließe bitte die App.',
    "restartForNormal":'Hinweis: Deine GPS-Daten werden wiederhergestellt, aber die GPS-Simulation dauert möglicherweise etwas länger, auch wenn sie bereits gestoppt wurde. Starte das iPhone besser neu, dann wird die GPS-Funktion wiederhergestellt.',
    "gotoPointErrorMsg":'Bewegen zum Zielstandort war nicht möglich. Der Eingabewert muss im GPS-Format vorliegen. Bitte versuche es erneut.',
    "gotoPointErrorTitle":'Bewegen nicht möglich',
    "pointModelTitle":'Bewegungsmodus',
    "lineModelTitle":'Gehmodus',
    "Distances":'Route/A-B Entfernungen',
    "Distances2":'Entfernungen',
    "TimeLeft":'Verbleibende Zeit',
    "mpointModelTitle":'Pin-Modus',
    "pause":'Pause',
    "run":'Start',
    "cycle":'Radfahren',
    "coord":'Koordination',
    "copyed":'In die Zwischenablage kopieren',
    "copyed1":"Teilen Sie es mit iTools-Benutzern",
    "emptyHistoryMessage":'Die Liste der Koordinaten ist leer',
    "historyDelMessage":'Soll dieses Element gelöscht werden?',
    "historySaveErrorMessage":'Der X/Y-Wert oder das Format sind nicht zulässig',
    "historySaveErrorTitle":'Fehlgeschlagen',
    "historyAddPlaceholder":'Deinen Positionsnamen eingeben',
    "confirmContent":'Bestätigen',
    "searchErrorMessage":'Leider keine Details oder Namen für Eingabe verfügbar:',
    "gpxErrFormat":'Leider ist das Format der abgelegten Datei unzulässig. Bitte Datei überprüfen und korrekte ablegen',
    "gpxErrRuning":'Leider ist der Gehen/Pin-Modus aktiv. Bitte die Fenster schließen und erneut versuchen',
    "exportMessage":'GPX-Datei exportieren',
    "returnLeft":'Deine bisherigen Koordinaten',
    "returnRight":'Auf "Zurück" klicken, um sofort zurückzukehren',
    "repeatModeMsg":'Tippe darauf, um zum Wiederholungsmodus zu wechseln',
    "repeatModeMsgDx":'Tippe darauf, um den Kreismodus zu wechseln',
    "tooFar":'Leider ist der Weg zu weit, um die Daten von der Google API abzurufen. Wechsle bitte in den Pin-Modus, um die Route zurückzusetzen',
    "gpxProgressTitle":'Erinnerung',
    "gpxProgressMessage":'Wir haben festgestellt, dass deine GPX mit deiner vorherigen identisch ist. Möchtest du fortfahren?',
    "group":'Gruppenname',
    "FromOrigin":'Vom Ursprung',
    "FromClipBoard":'Aus der Zwischenablage',
    "shortcut":'Verknüpfung',
    "yes":'Ja',
    "no":'Nein',
    "go":'Weiter',
    "return":'Zurück',
    "gotit":'Habe es',
    "error":'Fehler',
    "import":'Importieren',
    "export":'Exportieren',
    "holdoff":'Halten aus',
    "holdon":'Halten ein',
    "speed":'Geschwindigkeit',
    "importGpx":'GPX-Datei importieren',
    "findMe":'Auf mich zentrieren',
    "mapZommIn":'Karte vergrößern',
    "mapZommOut":'Karte verkleinern',
    "gpsError":'Falscher GPS-Wert',
    "upgpx":'GPX hochladen',
    "addFavorite":'Zu Favoriten hinzufügen',
    "unFavorite":'Aus Favoriten entfernen',
    "nearby":'In der Nähe',
    "favorites":'Favoriten',
    "search":'Suche',
    "nearbyInputMsg":'Entfernung eingeben (/m - /m)',
    "generate":'Erzeugen',
    "stops_gyms":'Stopps und Fitnessstudios',
    "stops":'Stopps',
    "gyms":'Fitnessstudios',
    "length":'Länge',
    "apply_it":'Anwenden',
    "comingsoon":'In Kürze',
    "nodata":'Keine Daten',
    "nearErrorInput":'Ungültige Nummer. Bitte im gültigen Bereich eingeben',
    "upgpxsuccess":'GPX wurde erfolgreich geladen',
    "upgpxfail":'Laden der GPX fehlgeschlagen',
    "addFavoriteSuccess":'Zu Favoriten hinzufügen erfolgreich',
    "addFavoriteFail":'Zu Favoriten hinzufügen fehlgeschlagen',
    "unFavoritesSuccess":'Löschen aus Favoriten erfolgreich',
    "unFavoritesFail":'Fehler beim Löschen aus Favoriten',
    "subscribe_active":'Aktivieren',
    "subscribe_success":'Erfolgreich',
    "subscribe_fail":'Fehlgeschlagen',
    "randomfactor":'Zufälliges Element hinzufügen, um wie ein Mensch zu gehen',
    "randomfactorkm":'km-Variable',
    "randomfactortime":'Sek. Ruhezeit',
    "unfold":'Funktionen ausklappen / ausblenden',
    "automove":'GPS-Driften',
    "netTip":'Das Netzwerk ist nicht verfügbar.',
    "gpsTip":'Der aktuelle Standort ist dein ursprünglicher Standort auf Basis deines Netzwerks. Gibt bitte die Fake-GPS-Position ein, und gehe zuerst dort hin, bevor du das GPS-Game öffnest.',
    "arrivedTip":'Am Ziel angekommen!',
    "deviceTip":'Dein Gerät wurde getrennt. Du kannst fortfahren, wenn eine Verbindung verfügbar ist.',
    "jsonTitle":'JSON-Liste',
    "gpxTitle":'GPX-Liste',
    "renameTitle":'Umbenennen',
    "renameBtn":'Umbenennen',
    "backBtn":'Rückseite',
    "doneBtn":'Fertig',
    "delBtn":'Löschen',
    "mapZoomTip": "Bitte zoomen Sie die Karte im 500-Meter-Maßstab, um alle Pokestops vollständig anzuzeigen",
  },
  "ko-KR": {
    "defense":"국방",
    "mystic":"신비한 팀",
    "valor":"영웅 팀",
    "instinct":"천재 팀",
    "team":"캠프",
    "own":"자신",
    "vacancy":"공석",
    "optRate":"최적의 비율",
    "gymInfo":"가능한 빨리이 위치에있는 파빌리온 및 공급 스테이션에 대한 정보를 업데이트 할 것입니다.",
    "region":"지역",
    "wildLife":"와일드",
    "battleInformation":"전투 정보",
    "greatleague":"슈퍼 리그",
    "ultraleague":"고위 리그",
    "masterleague":"마스터 리그",
    "atk":"공격",
    "sta":"국방",
    "hp":"체력",
    "power":"전투력",
    "opt":"전쟁 비율",
    "information":"정보",
    "frostbiteInfestation":"서리 내린 감염 지역",
    "showOnMap":"지도에 표시",
    "level":"등 급",
    "sourceText":"출처",
    "confirmed":"확인",
    "city":"도시",
    "cooldown":"냉각",
    "bouns":"보상",
    "researchTasks":"조사",
    "time":"시간",
    "sniperText":"저격수",
    "raidText":"팀 전투",
    "filedResrearch":"현장 조사",
    "addPoint":"이 점 추가",
    "minute":"분",
    "shiny_check":"반짝이는 체크",
    "feeds_noti":"피드 알림",
    "pokesniper":"PokeSniper",
    "imoportSuccessInfo":"가져 오기가 성공적으로 완료되었습니다. 가져 오기 데이터가 완료되지 않은 경우 나머지 부분을 제출하기 전에 텍스트 형식과 내용을 확인하고 수정하십시오.",
    "errorFormat":"수정 한 텍스트의 좌표 형식이 잘못되었습니다. 수정 한 후 다시 시도하십시오.",
    "importToList":"즐겨 찾기 목록 가져 오기",
    "choseImport":"가져 오는 방법 선택",
    "jsonFile":"로컬 json 파일",
    "textType":"텍스트 모드",
    "editGPX":"GPX 수정",
    "local":"지역",
    "text":"텍스트",
    "importSuccess":"수입 성공",
    "importFail":"가져 오기에 실패했습니다",
    "selectAll":"모두 선택",
    "nestsplaceholder":"필터링을위한 이름 / ID 입력",
    "lastUpdated":"마지막으로 업데이트 됨",
    "nests":"둥지",
    "noDeviceInfo":"주변기기가 연결되어 있지 않으면 푸시 기능이 허용되지 않습니다。",
    "country":"국가",
    "yield":"수율",
    "number":"번호",
    "addFavoritesSuccess":"좋아하는 네스트 정보가 좌표 컬렉션 목록에 추가되었습니다",
    "addFavorites":"즐겨 찾기에 추가",
    "newPokeStops":"도장 추가",
    "newGyms":"새로운 공급 스테이션",
    "report":"보고서",
    "generalSupply":"보통 공급",
    "generalInfection":"일반적인 감염 지역",
    "generalEncounter":"보통 만남",
    "generalRescue":"보통 구조 임무",
    "general":"공통",
    "errorDriftValue":"1에서 10까지의 정수를 입력하십시오.",
    "driftInterval":"한 번 드리프트",
    "frequency":"주파수",
    "drift":"현장 드리프트",
    "setting":"설정",
    "inputCity":"도시 이름이나 이니셜 검색어를 입력하십시오.",
    "locationText":"위치",
    "ifMakesure":'을 기본 언어로 선택 하시겠습니까?',
    "setDefaultLan":'/',
    "lanSet":'언어 설정',
    "simplifiedChinese":'/',
    "traditionalChinese":'/',
    "english":'/',
    "russian":'/',
    "german":'/',
    "korean":'한국어',
    "thai":'/',
    "vietnam":'/',
    "japan":'/',
    "reload":'다시 불러오기',
    "help":'도움말',
    "ifGo":'이동 여부',
    "all":'전체',
    "supply":'공급',
    "infectedArea":'감염',
    "encounter":'우연한 접전',
    "rescueMission":'구조 임무',
    "superiorHouse":'고급 주택',
    "armory":'병기고',
    "shelterValue":'아지트',
    "merchantStack":'교역 지점',
    "depot":'창고',
    "outpost":'레이더 전초 기지',
    "day":'일',
    "hour":'시간',
    "humanRaiders":'등급 레이더 기지지',
    "rare":'희귀 보급품',
    "epic":'역대급 보급품',
    "legend":'전설적인 보급품',
    "infectionRare":'희귀 감염',
    "infectionEpic":'역대급 감염',
    "infectionLegend":'전설급 감염',
    "encounterRare":'희귀 등급 우연한 접전',
    "encounterEpic":'역대급 우연한 접전',
    "encounterLegend":'전설급 우연한 접전',
    "rescueRare":'희귀한 구조 임무',
    "rescueEpic":'역대급 구조 임무',
    "rescueLegend":'전설적인 구조 임무',
    "ordnance":'등급 병기고 방어 시간',
    "shelter":'등급 아지트 방어 시간',
    "merchant":'등급 교역 지점 방어 시간',
    "warehouse":'등급 창고 방어 시간',
    "prompt":'메시지',
    "news":'푸시 메시지',
    "refresh":'새로 고침',
    "stopSim":'시뮬레이선 중지',
    "enterLoc":'주소/GPS 좌표 입력',
    "moveHere":'여기로 이동',
    "stopSimulation":'시뮬레이션을 중지하고 GPS 데이터 제어 해제(다른 iTools 모바일 앱 변환에 사용)',
    "stopSimulationInfo":'앱이 현재 작동하지 않습니다. 다시 사용할 준비가 되셨다면 다시 불러오기를 클릭하십시오. 다른 것을 사용할 준비가 되셨다면 앱을 닫으십시오.',
    "restartForNormal":'주의 사항: 귀하의 GPS 데이터가 복원되었지만 중지 후에도 GPS 시뮬레이션은 일정 시간 지속될 수 있습니다. GPS를 신속히 정상 작동하게 하려면 iPhone을 재부팅하는 것이 좋습니다.',
    "gotoPointErrorMsg":'목표 위치로 이동 실패. 입력값은 GPS 형식이어야 함. 재시도하십시오.',
    "gotoPointErrorTitle":'이동 실패',
    "pointModelTitle":'이동 모드',
    "lineModelTitle":'보행 모드',
    "Distances":'경로/A-B 거리',
    "Distances2":'거리',
    "TimeLeft":'남은 시간',
    "mpointModelTitle":'자유 경로 모드',
    "pause":'일단 정지',
    "run":'시작',
    "cycle":'순환',
    "coord":'좌표',
    "copyed":'클립보드에 복사',
    "copyed1":"iTools 사용자에게 공유",
    "emptyHistoryMessage":'좌표 목록이 비어 있음',
    "historyDelMessage":'이 항목을 삭제하시겠습니까?',
    "historySaveErrorMessage":'X/Y 수치 또는 형식 오류',
    "historySaveErrorTitle":'실패함',
    "historyAddPlaceholder":'제목을 입력하십시오.',
    "confirmContent":'확인',
    "searchErrorMessage":'입력 내용의 상세 정보 또는 이름이 없음:',
    "gpxErrFormat":'드래그된 파일의 형식 오류. 파일 확인 후 맞는 것을 드래그하십시오.',
    "gpxErrRuning":'보행/자유 경로 모드 실행 중. 윈도우를 닫고 다시 드래그하십시오.',
    "exportMessage":'GPX 파일 내보내기',
    "returnLeft":'이전 좌표',
    "returnRight":'‘돌아가기’를 클릭해 바로 돌아가기',
    "repeatModeMsg":'태핑해 반복 모드 변환하기',
    "repeatModeMsgDx":'태핑해 원형 모드 변환하기',
    "tooFar":'Google API로부터 데이터를 얻기에는 경로가 너무 멉니다. 자유 경로로 변환해 경로를 재설정하십시오.',
    "gpxProgressTitle":'미리 알림',
    "gpxProgressMessage":'드래그하는 GPX가 이전 것과 같습니다. 계속하시겠습니까?',
    "group":'그룹 이름',
    "FromOrigin":'혀재 지점',
    "FromClipBoard":'클립보드',
    "shortcut":'바로가기',
    "yes":'네',
    "no":'아니오',
    "go":'앞으로',
    "return":'뒤로',
    "gotit":'확인',
    "error":'에러',
    "import":'가져오기',
    "export":'내보내기',
    "holdoff":'잠금 해제',
    "holdon":'잠금',
    "speed":'속도',
    "importGpx":'GPX 파일 가져오기',
    "findMe":'내 위치',
    "mapZommIn":'지도 확대',
    "mapZommOut":'지도 축소',
    "gpsError":'잘못된 GPS 값',
    "upgpx":'GPX 업로드',
    "addFavorite":'즐겨찾기에 추가',
    "unFavorite":'바로가기 취소',
    "nearby":'주변',
    "favorites":'즐겨찾기',
    "search":'검색',
    "nearbyInputMsg":'거리 입력（/m - /m）',
    "generate":'생성',
    "stops_gyms":'보급 지점 및 수련장',
    "stops":'보급 지점',
    "gyms":'수련장',
    "length":'길이',
    "apply_it":'사용하기',
    "comingsoon":'곧 출시',
    "nodata":'데이터 없음',
    "nearErrorInput":'잘못된 번호. 유효한 범위로 입력하십시오.',
    "upgpxsuccess":'GPX 업로드됨',
    "upgpxfail":'GPX 업로드 실패',
    "addFavoriteSuccess":'즐겨찾기에 추가됨',
    "addFavoriteFail":'즐겨찾기 추가 실패',
    "unFavoritesSuccess":'즐겨찾기에서 삭제됨',
    "unFavoritesFail":'즐겨찾기에서 삭제 실패',
    "subscribe_active":'활성화하기',
    "subscribe_success":'성공',
    "subscribe_fail":'실패함',
    "randomfactor":'무작위 요소를 추가해 실제 보행처럼 시뮬레이션하기',
    "randomfactorkm":'km 변동값',
    "randomfactortime":'초 정지 시간',
    "unfold":'펼치기/감추기 기능',
    "automove":'GPS 표류',
    "netTip":'네트워크 이용이 불가.',
    "gpsTip":'현재 위치는 네트워크 상에서 귀하의 본래 위치입니다. GPS 게임을 기동하기 전에 임의의 gpS 위치를 입력하십시오.',
    "arrivedTip":'목적지 도착!',
    "deviceTip":'귀하의 장치가 연결 해제되었습니다. 접속 가능한 경우 계속할 수 있습니다.',
    "jsonTitle":'JSON 목록',
    "gpxTitle":'GPX 목록',
    "renameTitle":'이름 변경',
    "renameBtn":'이름 변경',
    "backBtn":'뒤로',
    "doneBtn":'완료',
    "delBtn":'삭제',
    "mapZoomTip": "모든 pokestops를 완전히 표시하려면 500 미터 측정 눈금 내에서지도를 확대하십시오.",
  },
  "th-TH": {
    "defense":"ฝ่ายจำเลย",
    "mystic":"ทีมลึกลับ",
    "valor":"ทีมฮีโร่",
    "instinct":"ทีมงานอัจฉริยะ",
    "team":"ค่าย",
    "own":"เป็นของ",
    "vacancy":"ห้อง",
    "optRate":"อัตราส่วนที่เหมาะสม",
    "gymInfo":"เราจะอัปเดตข้อมูลของศาลาและสถานีจัดหา ณ สถานที่นี้โดยเร็วที่สุด",
    "region":"ภูมิภาค",
    "wildLife":"ป่า",
    "battleInformation":"ข้อมูลการต่อสู้",
    "greatleague":"ซูเปอร์ลีก",
    "ultraleague":"ลีกอาวุโส",
    "masterleague":"มาสเตอร์ลีก",
    "atk":"โจมตี",
    "sta":"ฝ่ายจำเลย",
    "hp":"ความแข็งแรงทางกายภาพ",
    "power":"กำลังรบ",
    "opt":"อัตราส่วนของสงคราม",
    "information":"ข้อมูล",
    "frostbiteInfestation":"พื้นที่ที่ติดเชื้อ",
    "showOnMap":"แสดงบนแผนที่",
    "level":"ชั้นประถมศึกษาปี ฯลฯ",
    "sourceText":"แหล่ง",
    "confirmed":"ยืนยัน",
    "city":"เมือง",
    "cooldown":"คูลลิ่ง",
    "bouns":"รางวัล",
    "researchTasks":"การสอบสวน",
    "time":"เวลา",
    "sniperText":"นกปากซ่อม",
    "raidText":"การสู้รบของทีม",
    "filedResrearch":"การตรวจสอบภาคสนาม",
    "addPoint":"เพิ่มจุดนี้",
    "minute":"นาที",
    "shiny_check":"เช็คเงา",
    "feeds_noti":"การแจ้งข้อมูลฟีด",
    "pokesniper":"PokeSniper",
    "imoportSuccessInfo":"การนำเข้าสำเร็จแล้วหากข้อมูลการนำเข้าไม่สมบูรณ์โปรดตรวจสอบและแก้ไขรูปแบบข้อความและเนื้อหาก่อนที่จะส่งชิ้นส่วนที่เหลือ",
    "errorFormat":"ข้อความที่คุณแก้ไขมีรูปแบบพิกัดที่ไม่ถูกต้องโปรดตรวจสอบและแก้ไขและลองอีกครั้ง",
    "importToList":"นำเข้ารายการที่ชื่นชอบ",
    "choseImport":"เลือกวิธีการนำเข้า",
    "jsonFile":"ไฟล์ JSON ท้องถิ่น",
    "textType":"โหมดข้อความ",
    "editGPX":"แก้ไข GPX",
    "local":"ในประเทศ",
    "text":"ข้อความ",
    "importSuccess":"นำเข้าเรียบร้อยแล้ว",
    "importFail":"การนำเข้าล้มเหลว",
    "selectAll":"เลือกทั้งหมด",
    "nestsplaceholder":"ป้อนชื่อ / รหัสสำหรับการกรอง",
    "lastUpdated":"อัปเดตครั้งล่าสุดเมื่อวันที่",
    "nests":"รัง",
    "noDeviceInfo":"ไม่สามารถใช้งานฟังก์ชั่น Push หากไม่มีอุปกรณ์ต่อพ่วงใด ๆ。",
    "country":"ประเทศ",
    "yield":"เอาท์พุต",
    "number":"จำนวน",
    "addFavoritesSuccess":"ข้อมูลรังที่คุณชื่นชอบได้ถูกเพิ่มลงในรายการรวบรวมข้อมูลแล้ว",
    "addFavorites":"เพิ่มในรายการโปรด",
    "newPokeStops":"เพิ่มโดโจ",
    "newGyms":"สถานีอุปทานใหม่",
    "report":"รายงาน",
    "generalSupply":"อุปทานธรรมดา",
    "generalInfection":"บริเวณที่ติดเชื้อทั่วไป",
    "generalEncounter":"การเผชิญหน้าเป็นประจำ",
    "generalRescue":"ภารกิจช่วยเหลือสามัญ",
    "general":"สามัญ",
    "errorDriftValue":"โปรดป้อนจำนวนเต็มตั้งแต่ 1 ถึง 10",
    "driftInterval":"ล่องลอยครั้งเดียว",
    "frequency":"ความถี่",
    "drift":"การลอยตัวในที่เกิดเหตุ",
    "setting":"จัดตั้งขึ้น",
    "inputCity":"ป้อนชื่อเมืองหรือข้อความค้นหาชื่อย่อ",
    "locationText":"ที่ตั้ง",
    "ifMakesure":'คุณแน่ใจหรือไม่ว่าต้องการเลือก',
    "setDefaultLan":'เป็นภาษาเริ่มต้น',
    "lanSet":'การตั้งค่าภาษา',
    "simplifiedChinese":'/',
    "traditionalChinese":'/',
    "english":'/',
    "russian":'/',
    "german":'/',
    "korean":'/',
    "thai":'ไทย',
    "vietnam":'/',
    "japan":'/',
    "reload":'โหลดใหม่',
    "help":'วิธีใช้',
    "ifGo":'หากไป',
    "all":'ทั้งหมด',
    "supply":'การจัดหา',
    "infectedArea":'การติดเชื้อ',
    "encounter":'เผชิญหน้า',
    "rescueMission":'ภารกิจกู้ภัย',
    "superiorHouse":'บ้านของอธิการ',
    "armory":'คลังอาวุธ',
    "shelterValue":'ที่หลับภัย',
    "merchantStack":'ร้านค้าในที่กันดาร',
    "depot":'คลังสินค้า',
    "outpost":'ด่านหน้าของผู้โจมตี',
    "day":'วัน',
    "hour":'ชั่วโมง',
    "humanRaiders":'ระดับด่านหน้าของผู้โจมตี',
    "rare":'การจัดหาที่พบยาก',
    "epic":'การจัดหาที่ยิ่งใหญ่',
    "legend":'การจัดหาระดับตำนาน',
    "infectionRare":'การติดเชื้อที่พบยาก',
    "infectionEpic":'การติดเชื้อที่ยิ่งใหญ่',
    "infectionLegend":'การติดเชื้อระดับตำนาน',
    "encounterRare":'การเผชิญหน้าระดับหายาก',
    "encounterEpic":'การเผชิญหน้าที่ยิ่งใหญ่',
    "encounterLegend":'การเผชิญหน้าระดับตำนาน',
    "rescueRare":'ภารกิจกู้ภัยที่หายาก',
    "rescueEpic":'ภารกิจกู้ภัยที่ยิ่งใหญ่',
    "rescueLegend":'ภารกิจกู้ภัยระดับตำนาน',
    "ordnance":'ระดับเวลาการป้องกันคลังอาวุธ',
    "shelter":'ระดับเวลาการป้องกันที่หลบภัย',
    "merchant":'ระดับเวลาการป้องกันร้านค้าในที่กันดาร',
    "warehouse":'ระดับเวลาการป้องกันคลังสินค้า',
    "prompt":'ทันที',
    "news":'พุช',
    "refresh":'รีเฟรช',
    "stopSim":'หยุดการจำลอง',
    "enterLoc":'ป้อนที่อยู่/พิกัด GPS',
    "moveHere":'ย้ายตรงนี้',
    "stopSimulation":'หยุดการจำลองและปล่อยตัวควบคุมของข้อมูล GPS (มีการใช้เพื่อสลับแอปสำหรับโทรศัพท์มือถือ iTools)',
    "stopSimulationInfo":'แอปไม่ทำงานในขณะนี้ หากคุณพร้อมใช้งานอีกครั้ง โปรดคลิกปุ่มโหลดใหม่เพื่อใช้แอปอื่น โปรดปิดแอป',
    "restartForNormal":'หมายเหตุ: ข้อมูล GPS ของคุณถูกกู้คืนแล้ว แต่การจำลอง GPS อาจใช้เวลาสักครู่หนึ่งแม้ว่าคุณจะหยุดใช้งานแล้วก็ตาม คุณควรรีบูตเครื่อง iPhone เพื่อทำให้ GPS กลับมาเป็นปกติโดยไว',
    "gotoPointErrorMsg":'ไม่สามารถเคลื่อนย้ายไปยังตำแหน่งเป้าหมาย ค่าที่ป้อนต้องอยู่ในรูปแบบ GPS โปรดลองใหม่อีกครั้ง',
    "gotoPointErrorTitle":'ไม่สามารถเคลื่อนย้าย',
    "pointModelTitle":'โหมดเคลื่อนย้าย',
    "lineModelTitle":'โหมดเดิน',
    "Distances":'เส้นทาง/ระยะห่าง A-B',
    "Distances2":'ระยะห่าง',
    "TimeLeft":'เวลาคงเหลือ',
    "mpointModelTitle":'โหมดปักหมุด',
    "pause":'หยุดชั่วคราว',
    "run":'เริ่มต้น',
    "cycle":'รอบ',
    "coord":'พิกัด',
    "copyed":'คัดลอกลงในคลิปบอร์ด',
    "copyed1":"แบ่งปันให้กับผู้ใช้ iTools",
    "emptyHistoryMessage":'รายการพิกัดของคุณว่างเปล่า',
    "historyDelMessage":'คุณต้องการลบรายการนี้หรือไม่',
    "historySaveErrorMessage":'ค่า X/Y หรือรูปแบบไม่ถูกต้อง',
    "historySaveErrorTitle":'ล้มเหลว',
    "historyAddPlaceholder":'ป้อนชื่อหัวเรื่องของคุณ',
    "confirmContent":'ยืนยัน',
    "searchErrorMessage":'ขออภัย ไม่มีรายละเอียดหรือชื่อสำหรับอินพุต:',
    "gpxErrFormat":'ขออภัย รูปแบบของไฟล์ที่ลากมาไม่ถูกต้อง โปรดตรวจสอบไฟล์และลากไฟล์ที่ถูกต้อง',
    "gpxErrRuning":'ขออภัย โหมดเดิน/ปักหมุดกำลังทำงานอยู่ โปรดปิดหน้าต่างแล้วลองลากดูอีกครั้งหนึ่ง',
    "exportMessage":'ส่งออกไฟล์ GPX',
    "returnLeft":'พิกัดก่อนหน้าของคุร',
    "returnRight":'คลิกย้อนกลับเพื่อกลับทันที',
    "repeatModeMsg":'แตะเพื่อสลับโหมดทำซ้ำ',
    "repeatModeMsgDx":'แตะเพื่อสลับโหมดวงกลม',
    "tooFar":'ขออภัย เส้นทางไกลเกินไปที่จะได้รับข้อมูลจาก Google API โปรดสลับโหมดปักหมุดเพื่อรีเซ็ตเส้นทาง',
    "gpxProgressTitle":'การเตือนความจำ',
    "gpxProgressMessage":'เราได้ตรวจพบว่า GPX ที่ลากมาของคุณเป็นรายการเดียวกับข้อมูลเก่า คุณต้องการทำต่อหรือไม่',
    "group":'ชื่อกลุ่ม',
    "FromOrigin":'จากจุดเริ่มต้น',
    "FromClipBoard":'จากคลิปบอร์ด',
    "shortcut":'ทางลัด',
    "yes":'ใช่',
    "no":'ไม่',
    "go":'ไป',
    "return":'ย้อนกลับ',
    "gotit":'ถึงแล้ว',
    "error":'ข้อผิดพลาด',
    "import":'นำเข้า',
    "export":'ส่งออก',
    "holdoff":'กดปิดค้างไว้',
    "holdon":'กดเปิดค้างไว้',
    "speed":'ความเร็ว',
    "importGpx":'นำเข้าไฟล์ GPX',
    "findMe":'ตั้งจุดศูนย์กลางที่แน',
    "mapZommIn":'ขยายแผนที่',
    "mapZommOut":'ย่อแผนที่',
    "gpsError":'ค่า GPS ไม่ถูกต้อง',
    "upgpx":'อัปโหลด GPX',
    "addFavorite":'เพิ่มในรายการโปรด',
    "unFavorite":'ยกเลิกรายการโปรด',
    "nearby":'ใกล้เคียง',
    "favorites":'รายการโปรด',
    "search":'ค้นหา',
    "nearbyInputMsg":'ป้อนระยะห่าง (/ม - /ม)',
    "generate":'สร้าง',
    "stops_gyms":'จุดหยุดพักและยิม',
    "stops":'จุดหยุดพัก',
    "gyms":'ยิม',
    "length":'ความยาว',
    "apply_it":'ใช้มัน',
    "comingsoon":'กำลังจะมาเร็วๆ นี้',
    "nodata":'ไม่มีข้อมูล',
    "nearErrorInput":'หมายเลขไม่ถูกต้อง โปรดป้อนในช่วงที่ใช้งานได้',
    "upgpxsuccess":'การอัปโหลด GPX เสร็จเรียบร้อย',
    "upgpxfail":'การอัปโหลด GPX ไม่สำเร็จ',
    "addFavoriteSuccess":'การเพิ่มในรายการโปรดเสร็จเรียบร้อย',
    "addFavoriteFail":'การเพิ่มในรายการโปรดไม่สำเร็จ',
    "unFavoritesSuccess":'การลบออกจากรายการโปรดเสร็จเรียบร้อย',
    "unFavoritesFail":'การลบออกจากรายการโปรดไม่สำเร็จ',
    "subscribe_active":'เปิดใช้งาน',
    "subscribe_success":'เสร็จเรียบร้อย',
    "subscribe_fail":'ไม่สำเร็จ',
    "randomfactor":'เพิ่มส่วนประกอบแบบสุ่มเพื่อเดินให้เหมือนคนปกติ',
    "randomfactorkm":'กม. ที่แปรผัน',
    "randomfactortime":'วินาที เวลาหยุดนิ่ง',
    "unfold":'คุณสมบัติแสดง/ซ่อน',
    "automove":'การดริฟต์ GPS',
    "netTip":'เครือข่ายไม่สามารถใช้งานได้',
    "gpsTip":'ตำแหน่งที่ตั้งปัจจุบันคือตำแหน่งที่ตั้งเริ่มต้นของคุณโดยยึดตามเครือข่ายของคุณ โปรดป้อนตำแหน่งที่ตั้ง GPS ปลอมและย้ายไปตรงจุดนั้นก่อนที่คุณจะเปิดเกม GPS',
    "arrivedTip":'ถึงเป้าหมายแล้ว!',
    "deviceTip":'อุปกรณ์ของคุณถูกตัดการเชื่อมต่อ คุณสามารถไปข้างหน่า หากมีการเชื่อมต่อใช้งานได้',
    "jsonTitle":'รายการ JSON',
    "gpxTitle":'รายการ GPX',
    "renameTitle":'เปลี่ยนชื่อ',
    "renameBtn":'เปลี่ยนชื่อ',
    "backBtn":'ย้อนกลับ',
    "doneBtn":'เสร็จสิ้น',
    "delBtn":'ลบ',
    "mapZoomTip": "โปรดซูมแผนที่ภายในระยะวัด 500 เมตรเพื่อแสดง pokestops ทั้งหมด",
  },
  "vi-VN": {
    "defense":"Quốc phòng",
    "mystic":"Đội bí ẩn",
    "valor":"Đội anh hùng",
    "instinct":"Đội ngũ thiên tài",
    "team":"Trại",
    "own":"Riêng",
    "vacancy":"Vị trí tuyển dụng",
    "optRate":"Tỷ lệ tối ưu",
    "gymInfo":"Chúng tôi sẽ cập nhật thông tin của gian hàng và trạm cung cấp tại địa điểm này càng sớm càng tốt.",
    "region":"Khu vực",
    "wildLife":"Hoang dã",
    "battleInformation":"Thông tin trận chiến",
    "greatleague":"Siêu giải đấu",
    "ultraleague":"Giải đấu cao cấp",
    "masterleague":"Master League",
    "atk":"Tấn công",
    "sta":"Quốc phòng",
    "hp":"Thể lực",
    "power":"Sức mạnh chiến đấu",
    "opt":"Tỷ lệ chiến tranh",
    "information":"Thông tin",
    "frostbiteInfestation":"Khu vực nhiễm băng giá",
    "showOnMap":"Hiển thị trên bản đồ",
    "level":"Cấp độ",
    "sourceText":"Nguồn",
    "confirmed":"Xác nhận",
    "city":"Thành phố",
    "cooldown":"Làm mát",
    "bouns":"Phần thưởng",
    "researchTasks":"Điều tra",
    "time":"Thời gian",
    "sniperText":"Bắn tỉa",
    "raidText":"Đội chiến đấu",
    "filedResrearch":"Điều tra thực địa",
    "addPoint":"Thêm điểm này",
    "minute":"Phút",
    "shiny_check":"Kiểm tra sáng bóng",
    "feeds_noti":"Thông báo nguồn cấp dữ liệu",
    "pokesniper":"PokeSniper",
    "imoportSuccessInfo":"Nếu quá trình nhập dữ liệu chưa hoàn thành, vui lòng kiểm tra và sửa lại định dạng văn bản và nội dung trước khi gửi phần còn lại.",
    "errorFormat":"Văn bản bạn đã chỉnh sửa có định dạng tọa độ sai. Vui lòng kiểm tra và sửa đổi văn bản đó và thử lại.",
    "importToList":"Nhập danh sách yêu thích",
    "choseImport":"Chọn cách nhập",
    "jsonFile":"Tệp json cục bộ",
    "textType":"Chế độ văn bản",
    "editGPX":"Chỉnh sửa GPX",
    "local":"Địa phương",
    "text":"Văn bản",
    "importSuccess":"Đã nhập thành công",
    "importFail":"Không nhập được",
    "selectAll":"Chọn tất cả",
    "nestsplaceholder":"Nhập Tên / ID để lọc",
    "lastUpdated":"Cập nhật lần cuối lúc",
    "nests":"Tổ",
    "noDeviceInfo":"Chức năng đẩy không được phép nếu không có thiết bị ngoại vi nào được cắm vào。",
    "country":"Quốc gia",
    "yield":"Năng suất",
    "number":"Số",
    "addFavoritesSuccess":"Thông tin tổ yêu thích của bạn đã được thêm vào danh sách bộ sưu tập tọa độ",
    "addFavorites":"Thêm vào mục yêu thích",
    "newPokeStops":"Thêm dojo",
    "newGyms":"Trạm cung cấp mới",
    "report":"Báo cáo",
    "generalSupply":"Cung cấp bình thường",
    "generalInfection":"Khu vực bị nhiễm thông thường",
    "generalEncounter":"Cuộc gặp gỡ thông thường",
    "generalRescue":"Sứ mệnh cứu hộ thông thường",
    "general":"Chung",
    "errorDriftValue":"Vui lòng nhập số nguyên từ 1 đến 10",
    "driftInterval":"Trôi một lần",
    "frequency":"Tần số",
    "drift":"Trôi tại chỗ",
    "setting":"Cài đặt",
    "inputCity":"Nhập tên thành phố hoặc truy vấn tắt",
    "locationText":"Địa điểm",
    "ifMakesure":'Bạn có chắc chắn muốn chọn',
    "setDefaultLan":'làm ngôn ngữ mặc định không?',
    "lanSet":'Cài đặt ngôn ngữ',
    "simplifiedChinese":'/',
    "traditionalChinese":'/',
    "english":'/',
    "russian":'/',
    "german":'/',
    "korean":'/',
    "thai":'/',
    "vietnam":'Người việt nam',
    "japan":'/',
    "reload":'Tải lại',
    "help":'Trợ giúp',
    "ifGo":'nếu bắt đầu',
    "all":'Tất cả',
    "supply":'Nguồn cung',
    "infectedArea":'Lây nhiễm',
    "encounter":'Đối đầu',
    "rescueMission":'Nhiệm vụ giải cứu',
    "superiorHouse":'Nhà cao cấp',
    "armory":'Kho vũ khí',
    "shelterValue":'Nơi trú ẩn',
    "merchantStack":'Nơi giao dịch',
    "depot":'Nhà kho',
    "outpost":'Tiền đồn địch',
    "day":'ngày',
    "hour":'giờ',
    "humanRaiders":'tiền đồn địch cấp-',
    "rare":'Nguồn cung hiếm',
    "epic":'Nguồn cung lịch sử',
    "legend":'Nguồn cung huyền thoại',
    "infectionRare":'Lây nhiễm hiếm',
    "infectionEpic":'Lây nhiễm lịch sử',
    "infectionLegend":'Lây nhiễm huyền thoại',
    "encounterRare":'Đối đầu cấp hiếm',
    "encounterEpic":'Đối đầu lịch sử',
    "encounterLegend":'Đối đầu huyền thoại',
    "rescueRare":'Nhiệm vụ giải cứu hiếm',
    "rescueEpic":'Nhiệm vụ giải cứu lịch sử',
    "rescueLegend":'Nhiệm vụ giải cứu huyền thoại',
    "ordnance":'thời gian bảo vệ kho vũ khí cấp-',
    "shelter":'thời gian bảo vệ nơi trú ẩn cấp-',
    "merchant":'thời gian bảo vệ nơi giao dịch cấp-',
    "warehouse":'thời gian bảo vệ nhà kho cấp-',
    "prompt":'Nhắc nhở',
    "news":'Đẩy',
    "refresh":'Làm mới',
    "stopSim":'Ngừng Mô Phỏng',
    "enterLoc":'Nhập tọa độ địa chỉ/GPS',
    "moveHere":'Đi tới đây',
    "stopSimulation":'Ngừng mô phỏng và cho phép kiểm soát dữ liệu GPS (được sử dụng để chuyển đổi các ứng dụng di động iTools khác nhau)',
    "stopSimulationInfo":'Ứng dụng hiện không hoạt động Nếu bạn sẵn sàng sử dụng lại vui lòng nhấp nút tải lại Nếu bạn sẵn sàng sử dụng ứng dụng khác vui lòng đóng ứng dụng này',
    "restartForNormal":'Lưu ý: Dữ liệu GPS của bạn đã được khôi phục Nhưng thao tác mô phỏng GPS có thể tiếp tục trong một thời gian dù bạn đã dừng Bạn nên khởi động lại iPhone để GPS sớm trở lại bình thường',
    "gotoPointErrorMsg":'Không thể di chuyển đến vị trí mục tiêu Giá trị đầu vào phải ở định dạng GPS Vui lòng thử lại',
    "gotoPointErrorTitle":'Không thể di chuyển',
    "pointModelTitle":'Chế độ di chuyển',
    "lineModelTitle":'Chế độ đi bộ',
    "Distances":'Khoảng cách quãng đường/A-B',
    "Distances2":'Khoảng cách',
    "TimeLeft":'Thời gian còn lại',
    "mpointModelTitle":'Chế độ pin',
    "pause":'Tạm dừng',
    "run":'Bắt đầu',
    "cycle":'Chu kỳ',
    "coord":'Tọa độ',
    "copyed":'Sao chép vào bản ghi tạm',
    "copyed1":"Chia sẻ với người dùng iTools",
    "emptyHistoryMessage":'Danh sách tọa độ của bạn trống',
    "historyDelMessage":'Bạn có muốn xóa mục này?',
    "historySaveErrorMessage":'Giá trị X/Y hoặc định dạng không hợp lệ',
    "historySaveErrorTitle":'Không thành công',
    "historyAddPlaceholder":'Nhập tên tiêu đề của bạn',
    "confirmContent":'Xác nhận',
    "searchErrorMessage":'Rất tiếc, không có chi tiết hoặc tên nào thích hợp với đầu vào:',
    "gpxErrFormat":'Rất tiếc, định dạng tập tin đã kéo là không hợp lệ Vui lòng kiểm tra tập tin và kéo tập tin chính xác',
    "gpxErrRuning":'Rất tiếc, Chế Độ Đi Bộ/Ghim đang chạy Vui lòng đóng cửa sổ và thử kéo lại',
    "exportMessage":'Xuất tập tin GPX',
    "returnLeft":'Tọa độ trước đây của bạn',
    "returnRight":'Nhấp vào Return (Quay Lại) để quay lại ngay lập tức',
    "repeatModeMsg":'Nhấn vào nó để chuyển sang Chế Độ Lặp Lại',
    "repeatModeMsgDx":'Nhấn vào nó để chuyển sang Chế Độ Vòng Tròn',
    "tooFar":'Rất tiếc, tuyến đường quá xa để có thể lấy dữ liệu từ Google API. Vui lòng chuyển sang Chế Độ Ghim để đặt lại tuyến đường',
    "gpxProgressTitle":'Nhắc nhở',
    "gpxProgressMessage":'Chúng tôi đã phát hiện thấy GPX đang kéo của bạn giống với GPX trước đó Bạn có muốn tiếp tục không?',
    "group":'Tên nhóm',
    "FromOrigin":'Từ Gốc',
    "FromClipBoard":'Từ Khay Nhớ Tạm',
    "shortcut":'Lối tắt',
    "yes":'Có',
    "no":'Không',
    "go":'Đi',
    "return":'Quay lại',
    "gotit":'Được rồi',
    "error":'Lỗi',
    "import":'Nhập',
    "export":'Xuất',
    "holdoff":'Chờ',
    "holdon":'Ngừng lại',
    "speed":'Tốc độ',
    "importGpx":'Nhập tập tin GPX',
    "findMe":'Tập trung vào tôi',
    "mapZommIn":'Phóng to bản đồ',
    "mapZommOut":'Thu nhỏ bản đồ',
    "gpsError":'Giá trị GPS sai',
    "upgpx":'Tải lên GPX',
    "addFavorite":'Thêm vào Mục Yêu Thích',
    "unFavorite":'Không Yêu Thích',
    "nearby":'Gần Đây',
    "favorites":'Yêu Thích',
    "search":'Tìm Kiếm',
    "nearbyInputMsg":'Nhập khoảng cách（/m - /m）',
    "generate":'Tạo',
    "stops_gyms":'Điểm Dừng & Phòng Tập Thể Dục',
    "stops":'Điểm Dừng',
    "gyms":'Phòng Tập Thể Dục',
    "length":'Chiều dài',
    "apply_it":'Áp dụng nó',
    "comingsoon":'Sắp Ra Mắt',
    "nodata":'Không Có Dữ Liệu',
    "nearErrorInput":'Số không hợp lệ Vui lòng nhập trong phạm vi hiệu lực của nó',
    "upgpxsuccess":'Tải lên thành công GPX',
    "upgpxfail":'Tải lên GPX không thành công',
    "addFavoriteSuccess":'Thêm vào Mục Yêu Thích thành công',
    "addFavoriteFail":'Thêm vào Favorites Mục Yêu Thích không thành công',
    "unFavoritesSuccess":'Xóa nó khỏi Mục Yêu Thích thành công',
    "unFavoritesFail":'Xóa nó khỏi Mục Yêu Thích không thành công',
    "subscribe_active":'Kích hoạt',
    "subscribe_success":'Thành công',
    "subscribe_fail":'Không thành công',
    "randomfactor":'Thêm yếu tố ngẫu nhiên để đi bộ như một con người',
    "randomfactorkm":'biến số km',
    "randomfactortime":'giây còn lại',
    "unfold":'Mở / Ẩn các tính năng',
    "automove":'Thay Đổi GPS',
    "netTip":'Mạng không khả dụng.',
    "gpsTip":'Vị trí hiện tại là vị trí ban đầu của bạn dựa trên mạng của bạn. Vui lòng nhập vị trí gps giả và di chuyển đến đó trước khi bạn mở trò chơi GPS.',
    "arrivedTip":'đã đến đích!',
    "deviceTip":'Thiết bị của bạn đã bị ngắt kết nối. Bạn có thể tiếp tục nếu kết nối khả dụng.',
    "jsonTitle":'Danh Sách JSON',
    "gpxTitle":'Danh Sách GPX',
    "renameTitle":'Đổi tên',
    "renameBtn":'Đổi tên',
    "backBtn":'Trở lại',
    "doneBtn":'Hoàn tất',
    "delBtn":'Xóa',
    "mapZoomTip": "Vui lòng phóng to bản đồ trong phạm vi 500 mét để hiển thị tất cả các pokestops hoàn toàn",
  },
  "ja-JP": {
    "defense":"防衛",
    "mystic":"神秘的なチーム",
    "valor":"英雄チーム",
    "instinct":"天才チーム",
    "team":"キャンプ",
    "own":"自分の",
    "vacancy":"欠員",
    "optRate":"最適な比率",
    "gymInfo":"この場所にあるパビリオンとサプライステーションの情報をできるだけ早く更新します。",
    "region":"地域",
    "wildLife":"ワイルド",
    "battleInformation":"バトル情報",
    "greatleague":"スーパーリーグ",
    "ultraleague":"シニアリーグ",
    "masterleague":"マスターリーグ",
    "atk":"アタック",
    "sta":"防衛",
    "hp":"体力",
    "power":"戦闘力",
    "opt":"戦争率",
    "information":"情報",
    "frostbiteInfestation":"凍傷感染地域",
    "showOnMap":"地図上に表示する",
    "level":"等級",
    "sourceText":"ソース",
    "confirmed":"確認",
    "city":"都市",
    "cooldown":"冷却",
    "bouns":"報酬",
    "researchTasks":"調査",
    "time":"時間",
    "sniperText":"スナイパー",
    "raidText":"チームバトル",
    "filedResrearch":"現地調査",
    "addPoint":"このポイントを追加",
    "minute":"分",
    "shiny_check":"シャイニーチェック",
    "feeds_noti":"フィード通知",
    "pokesniper":"PokeSniper",
    "imoportSuccessInfo":"导入成功.インポートが正常に完了していない場合は、残りの部分を提出する前に、テキスト形式と内容を確認して修正してください.",
    "errorFormat":"編集したテキストの座標形式が間違っています。確認して修正してからもう一度お試しください",
    "importToList":"お気に入りリストをインポートする",
    "choseImport":"インポート方法の選択",
    "jsonFile":"ローカルjsonファイル",
    "textType":"テキストモード",
    "editGPX":"GPXを編集する",
    "local":"ローカル",
    "text":"テキスト",
    "importSuccess":"インポートに成功しました",
    "importFail":"インポートに失敗しました",
    "selectAll":"すべて選択",
    "nestsplaceholder":"フィルタリングのための名前/ IDを入力してください",
    "lastUpdated":"最終更新日",
    "nests":"巣",
    "noDeviceInfo":"ペリフェラルが接続されていない場合、プッシュ機能は使用できません。",
    "country":"国",
    "yield":"収量",
    "number":"番号",
    "addFavoritesSuccess":"お気に入りのネスト情報が座標コレクションリストに追加されました",
    "addFavorites":"お気に入りに追加",
    "newPokeStops":"道場を追加する",
    "newGyms":"新しい供給ステーション",
    "report":"レポート",
    "generalSupply":"普通の供給",
    "generalInfection":"一般的な感染地域",
    "generalEncounter":"普通の出会い",
    "generalRescue":"普通救助使命",
    "general":"共通",
    "errorDriftValue":"1〜10の整数を入力してください",
    "driftInterval":"一度ドリフト",
    "frequency":"周波数",
    "drift":"その場でのドリフト",
    "setting":"設定",
    "inputCity":"都市名またはイニシャルクエリを入力してください",
    "locationText":"場所",
    "ifMakesure":'をデフォルトの言語として選択してもよろしいですか？',
    "setDefaultLan":'/',
    "lanSet":'言語設定',
    "simplifiedChinese":'/',
    "traditionalChinese":'/',
    "english":'/',
    "russian":'/',
    "german":'/',
    "korean":'/',
    "thai":'/',
    "vietnam":'/',
    "japan":'日本語',
    "reload":'リロード',
    "help":'ヘルプ',
    "ifGo":'もし行けば',
    "all":'すべて',
    "supply":'サプライ',
    "infectedArea":'感染',
    "encounter":'遭遇',
    "rescueMission":'レスキューミッション',
    "superiorHouse":'スーペリアハウス',
    "armory":'武器',
    "shelterValue":'シェルター',
    "merchantStack":'トレードポスト',
    "depot":'倉庫',
    "outpost":'ライダーの前哨',
    "day":'日',
    "hour":'時間',
    "humanRaiders":'-レベルのライダーの前哨',
    "rare":'レアなサプライ',
    "epic":'大規模なサプライ',
    "legend":'伝説のサプライ',
    "infectionRare":'レアな感染',
    "infectionEpic":'大規模な感染',
    "infectionLegend":'伝説の感染',
    "encounterRare":'レアなレベルの遭遇',
    "encounterEpic":'大規模な遭遇',
    "encounterLegend":'伝説の遭遇',
    "rescueRare":'レアなレスキューミッション',
    "rescueEpic":'大規模なレスキューミッション',
    "rescueLegend":'伝説のレスキューミッション',
    "ordnance":'=-レベルの武器防御タイム',
    "shelter":'=-レベルのシェルター防御タイム',
    "merchant":'-レベルのトレードポスト防御タイム',
    "warehouse":'-レベルの倉庫防御タイム',
    "prompt":'プロンプト',
    "news":'プッシュ',
    "refresh":'更新',
    "stopSim":'シミュレーションを停止',
    "enterLoc":'adr / GPS座標を入力',
    "moveHere":'ここに移動',
    "stopSimulation":'シミュレーションを停止して、GPS データの制御を解除（異なるiToolsモバイルアプリの切り替えに使用）',
    "stopSimulationInfo":'現在アプリが動作していません　もう一度使用する準備ができている場合は、リロードボタンをクリックしてください　別のアプリを使用する準備ができている場合は、アプリを閉じてください',
    "restartForNormal":'お知らせ：GPSデータは回復しました。しかし、GPSシミュレーションは、停止してもしばらくの間続行する可能性があります　iPhoneを再起動してGPSを正常な状態にすぐに戻すことをお勧めします',
    "gotoPointErrorMsg":'ターゲットの場所に移動できませんでした入力した値はGPS形式である必要があります もう一度やり直してください',
    "gotoPointErrorTitle":'移動に失敗しました',
    "pointModelTitle":'移動モード',
    "lineModelTitle":'ウォークモード',
    "Distances":'ルート/ A-B間の距離',
    "Distances2":'距離',
    "TimeLeft":'残り時間',
    "mpointModelTitle":'ピンモード',
    "pause":'一時停止',
    "run":'スタート',
    "cycle":'サイクル',
    "coord":'座標',
    "copyed":'クリップボードにコピー',
    "copyed1":"iToolsユーザーに共有する",
    "emptyHistoryMessage":'あなたの座標リストは空です',
    "historyDelMessage":'このアイテムを本当に削除しますか？',
    "historySaveErrorMessage":'X/Y値またはフォーマットが不正です',
    "historySaveErrorTitle":'エラー',
    "historyAddPlaceholder":'見出しの名前を入力してください',
    "confirmContent":'確認する',
    "searchErrorMessage":'申し訳ありません、入力の詳細や名称はありません：',
    "gpxErrFormat":'申し訳ありません ドラッグしたファイルのフォーマットが不正です ファイルをチェックし、正しいものをドラッグしてください',
    "gpxErrRuning":'申し訳ありません ウォーク/ピンモードが実行中です ウィンドウを閉じもう一度ドラッグしてみてください',
    "exportMessage":'GPXファイルをエクスポート',
    "returnLeft":'あなたの以前の座標',
    "returnRight":'戻るをクリックして、一度戻ってください',
    "repeatModeMsg":'タップしてリピートモードに切り替えます',
    "repeatModeMsgDx":'タップしてサークルモードに切り替えます',
    "tooFar":'Google APIからデータを取得するにはルートが長すぎます ピンモードを切り替えてルートをリセットしてください',
    "gpxProgressTitle":'リマインダ',
    "gpxProgressMessage":'ドラッグしているGPXが以前のものと同じであることを検出しました。本当に続行しますか？',
    "group":'グループ名',
    "FromOrigin":'原点から',
    "FromClipBoard":'クリップボードから',
    "shortcut":'ショートカット',
    "yes":'はい',
    "no":'いいえ',
    "go":'進む',
    "return":'戻る',
    "gotit":'分かりました',
    "error":'エラー',
    "import":'インポート',
    "export":'エキスポート',
    "holdoff":'延期',
    "holdon":'待機',
    "speed":'速度',
    "importGpx":'GPXファイルをインポート',
    "findMe":'自分を中心に',
    "mapZommIn":'マップでのズームイン',
    "mapZommOut":'マップでのズームアウト',
    "gpsError":'間違ったGPS値',
    "upgpx":'GPXをアップロード',
    "addFavorite":'お気に入りに追加',
    "unFavorite":'お気に入りではない',
    "nearby":'近く',
    "favorites":'お気に入り',
    "search":'サーチ',
    "nearbyInputMsg":'距離を入力（/m - /m）',
    "generate":'生成',
    "stops_gyms":'ストップ＆ジム',
    "stops":'ストップ',
    "gyms":'ジム',
    "length":'長さ',
    "apply_it":'適用',
    "comingsoon":'近日発売',
    "nodata":'データがありません',
    "nearErrorInput":'無効な番号　有効範囲内に入力してください',
    "upgpxsuccess":'GPXのアップロードが完了しました',
    "upgpxfail":'GPXのアップロードに失敗しました',
    "addFavoriteSuccess":'お気に入りに追加しました',
    "addFavoriteFail":'お気に入りへの追加に失敗しました',
    "unFavoritesSuccess":'お気に入りから削除しました',
    "unFavoritesFail":'お気に入りからの削除に失敗しました',
    "subscribe_active":'有効化',
    "subscribe_success":'完了',
    "subscribe_fail":'エラー',
    "randomfactor":'ランダム要素を追加し人間として歩く',
    "randomfactorkm":'km変数',
    "randomfactortime":'秒の静止時間',
    "unfold":'機能の展開/非表示',
    "automove":'GPSドリフト',
    "netTip":'ネットワークが利用できません。',
    "gpsTip":'現在の場所は、ネットワークに基づいた元の場所です。GPSゲームを開く前に、最初にフェイクのGPSの場所を入力して移動してください。',
    "arrivedTip":'目標に到着！',
    "deviceTip":'お使いのデバイスが切断されています。接続が利用できる場合、先に進むことができます。',
    "jsonTitle":'JSON リスト',
    "gpxTitle":'GPX リスト',
    "renameTitle":'再度名前を変更',
    "renameBtn":'再度名前を変更',
    "backBtn":'戻る',
    "doneBtn":'完了',
    "delBtn":'削除',
    "mapZoomTip": "すべてのポケストを完全に表示するには、500メートルの測定スケール内で地図をズームインしてください",
  },
  lanCode:{
    'zh-CN':'tw',
    'zh-TW':'tw',
    'en-US':'en',
    'ru-RU':'ru',
    'de-DE':'de',
    'ko-KR':'ko',
    'th-TH':'en',
    'vi-VN':'en',
    'ja-JP':'ja',
    'es-ES':'es',
    'fr-FR':'fr',
    'pt-PT':'pt',
    'it-IT':'it',
  },
  codeToTitle:{
    "zh-CN":"tw_title",
    'zh-TW':'tw_title',
    "en-US":"en_title",
    "de-DE":"de_title",
    "fr-FR":"fr_title",
    "pt-PT":"pt_title",
    "ja-JP":"ja_title",
    "it-IT":"it_title",
    "ko-KR":"ko_title",
    "vi-VN":"en_title",//没有越南语
    "th-TH":"en_title", //没有泰语
    "ru-RU":"en_title" //没有俄语ru_title
  },
  languages:[
    {
      key:'zh-CN',
      value:'简体中文',
    },{
      key:'zh-TW',
      value:'繁體中文',
    },{
      key:'en-US',
      value:'English',
    },{
      key:'ru-RU',
      value:'русский',
    },{
      key:'de-DE',
      value:'Deutsch',
    },{
      key:'ko-KR',
      value:'한국어',
    },{
      key:'th-TH',
      value:'ไทย',
    },{
      key:'vi-VN',
      value:'Người việt nam',
    },{
      key:'ja-JP',
      value:'日本語',
    }]
}

export default TRANS;
